/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.cobach.vista;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import mx.edu.cobach.persistencia.entidades.Evento;
import mx.edu.cobach.persistencia.entidades.Departamento;
import mx.edu.cobach.persistencia.entidades.Direccion;
import mx.edu.cobach.persistencia.entidades.Empleado;
import mx.edu.cobach.persistencia.entidades.EnunciadoLogistica;
import mx.edu.cobach.persistencia.entidades.ImplementacionEvento;
import mx.edu.cobach.persistencia.entidades.ImplementacionEventoEnunciadoLogistica;
import mx.edu.cobach.persistencia.entidades.Plantel;
import mx.edu.cobach.persistencia.entidades.Proveedor;
import mx.edu.cobach.persistencia.entidades.Puesto;
import mx.edu.cobach.persistencia.entidades.Sede;
import mx.edu.cobach.vista.controlador.DataHelper;
import mx.edu.cobach.vista.controlador.ImplementarEventoControlador;

/**
 * Esta clase mostrara la interfaz de los eventos a realizar, agregando el
 * proveedor del eventp, la sede sus respectivas fechas igual o inferiores a la
 * actual y la lista de asistencia
 *
 * @author liuts
 */
public class PnlEventoRealizado extends javax.swing.JPanel implements
        Comunicador, FocusListener {

    /**
     * Creates new form PnlEventoRealizado
     */
    private static ImplementarEventoControlador control;
    private int eventoProgramarId;
    private final DefaultComboBoxModel sedeModel;
    private final DefaultComboBoxModel proveedorModel;
    private final DefaultTableModel modelTablaEn;
    private final DefaultTableModel modelTablaEmF;
    private final String[] titulosTablaEn = {"ID", "Tipo", "Enunciado",
        "Calificación"};
    private final String[] titulosTablaEm = {"Numero",
        "Nombre del Empleado"};
    private Evento evento;
    private boolean cambio = false;
    private CapacisoftFrm capacisoft;

    public PnlEventoRealizado(CapacisoftFrm capacisoft) {
        this.capacisoft = capacisoft;
        initComponents();
        sedeModel = new DefaultComboBoxModel();
        proveedorModel = new DefaultComboBoxModel();

        modelTablaEn = new DefaultTableModel(titulosTablaEn, 0);
        enunciadoTbl.setModel(modelTablaEn);
        enunciadoTbl.setColumnSelectionAllowed(false);
        enunciadoTbl.setDragEnabled(false);

        modelTablaEmF = new DefaultTableModel(titulosTablaEm, 0);
        listaAsistenciaTbl.setModel(modelTablaEmF);
        listaAsistenciaTbl.setColumnSelectionAllowed(false);
        listaAsistenciaTbl.setDragEnabled(false);

        tipoSedeGCBx.setModel(sedeModel);
        nombreGCBx.setModel(proveedorModel);
        control = new ImplementarEventoControlador(this,
                ImplementacionEvento.class);
        fechaIDCh.getJCalendar().setMaxSelectableDate(new Date());
        fechaTDCh.getJCalendar().setMaxSelectableDate(new Date());
        informacionTBn.setEnabledAt(0, true);
        informacionTBn.setEnabledAt(1, false);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(0);
        tabla();
        fechaIDCh.addFocusListener(this);
        tipoSedeGCBx.addFocusListener(this);
        nombreGCBx.addFocusListener(this);
        validFechIniLbl.setVisible(false);
        validSedeLbl.setVisible(false);
        validProveedorLbl.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionTBn = new javax.swing.JTabbedPane();
        generalPnl = new javax.swing.JPanel();
        nombreGLbl = new javax.swing.JLabel();
        fechaILbl = new javax.swing.JLabel();
        fechaTLbl = new javax.swing.JLabel();
        tipoGLbl = new javax.swing.JLabel();
        sedeGLbl = new javax.swing.JLabel();
        nombrePrLbl = new javax.swing.JLabel();
        nombreGTFd = new javax.swing.JTextField();
        tipoGCBx = new javax.swing.JComboBox();
        tipoSedeGCBx = new javax.swing.JComboBox();
        nombreGCBx = new javax.swing.JComboBox();
        siguienteGBtn = new javax.swing.JButton();
        fechaIDCh = new com.toedter.calendar.JDateChooser();
        fechaTDCh = new com.toedter.calendar.JDateChooser();
        generalLbl = new javax.swing.JLabel();
        generalMsjLbl = new javax.swing.JLabel();
        cancelarGBtn = new javax.swing.JButton();
        validFechIniLbl = new javax.swing.JLabel();
        validProveedorLbl = new javax.swing.JLabel();
        validSedeLbl = new javax.swing.JLabel();
        listaPnl = new javax.swing.JPanel();
        listaAsistenciaMsjLbl = new javax.swing.JLabel();
        listaAsistenciaSPn = new javax.swing.JScrollPane();
        listaAsistenciaTbl = new javax.swing.JTable();
        siguienteLABtn = new javax.swing.JButton();
        listaAsistenciaLbl = new javax.swing.JLabel();
        registroMsjLbl = new javax.swing.JLabel();
        generarBtn = new javax.swing.JButton();
        registroLbl = new javax.swing.JLabel();
        cancelarLABtn = new javax.swing.JButton();
        regresarLABtn = new javax.swing.JButton();
        calificacionPnl = new javax.swing.JPanel();
        guardarCBtn = new javax.swing.JButton();
        enunciadoSPn = new javax.swing.JScrollPane();
        enunciadoTbl = new javax.swing.JTable();
        calificacionLbl = new javax.swing.JLabel();
        calificacionMsjLbl = new javax.swing.JLabel();
        cancelarCBtn = new javax.swing.JButton();
        regresarCBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        informacionTBn.setPreferredSize(new java.awt.Dimension(739, 472));

        generalPnl.setPreferredSize(new java.awt.Dimension(766, 548));
        generalPnl.setRequestFocusEnabled(false);

        nombreGLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreGLbl.setText("Nombre del evento:");

        fechaILbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaILbl.setText("Fecha inicial de evento*:");

        fechaTLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaTLbl.setText("Fecha de terminación del evento:");

        tipoGLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoGLbl.setText("Tipo de evento:");

        sedeGLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sedeGLbl.setText("Sede del evento*:");

        nombrePrLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombrePrLbl.setText("Nombre de Proveedor*:");

        nombreGTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreGTFd.setEnabled(false);

        tipoGCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoGCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CONFERENCIA", "TALLER", "CURSO", "CURSO / TALLER", "PLATICA" }));
        tipoGCBx.setEnabled(false);
        tipoGCBx.setMaximumSize(new java.awt.Dimension(100, 23));

        tipoSedeGCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoSedeGCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoSedeGCBx.setEnabled(false);
        tipoSedeGCBx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoSedeGCBxItemStateChanged(evt);
            }
        });

        nombreGCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreGCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nombreGCBx.setEnabled(false);
        nombreGCBx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreGCBxItemStateChanged(evt);
            }
        });

        siguienteGBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siguienteGBtn.setText("Siguiente");
        siguienteGBtn.setEnabled(false);
        siguienteGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteGBtnActionPerformed(evt);
            }
        });

        fechaIDCh.setDateFormatString("dd/MM/yyyy");
        fechaIDCh.setEnabled(false);

        fechaTDCh.setDateFormatString("dd/MM/yyyy");
        fechaTDCh.setEnabled(false);

        generalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generalLbl.setText("Registro");

        generalMsjLbl.setText("Ingrese la información a almacenar, para salir o cancelar el registro presione el botón \"Cancelar\"");

        cancelarGBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarGBtn.setText("Cancelar");
        cancelarGBtn.setEnabled(false);
        cancelarGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarGBtnActionPerformed(evt);
            }
        });

        validFechIniLbl.setForeground(new java.awt.Color(240, 0, 0));
        validFechIniLbl.setText("Este campo es obligatorio");

        validProveedorLbl.setForeground(new java.awt.Color(240, 0, 0));
        validProveedorLbl.setText("Este campo es obligatorio");

        validSedeLbl.setForeground(new java.awt.Color(240, 0, 0));
        validSedeLbl.setText("Este campo es obligatorio");

        javax.swing.GroupLayout generalPnlLayout = new javax.swing.GroupLayout(generalPnl);
        generalPnl.setLayout(generalPnlLayout);
        generalPnlLayout.setHorizontalGroup(
            generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPnlLayout.createSequentialGroup()
                        .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreGLbl)
                            .addComponent(generalLbl)
                            .addComponent(generalMsjLbl)
                            .addGroup(generalPnlLayout.createSequentialGroup()
                                .addGap(459, 459, 459)
                                .addComponent(cancelarGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(siguienteGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(generalPnlLayout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaTDCh, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombreGTFd, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                        .addComponent(tipoGCBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(validFechIniLbl)
                                        .addComponent(fechaIDCh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(generalPnlLayout.createSequentialGroup()
                        .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaILbl)
                            .addComponent(tipoGLbl)
                            .addComponent(fechaTLbl)
                            .addGroup(generalPnlLayout.createSequentialGroup()
                                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sedeGLbl)
                                    .addComponent(nombrePrLbl))
                                .addGap(81, 81, 81)
                                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(validProveedorLbl)
                                    .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(validSedeLbl)
                                        .addComponent(tipoSedeGCBx, 0, 380, Short.MAX_VALUE)
                                        .addComponent(nombreGCBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        generalPnlLayout.setVerticalGroup(
            generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(generalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalMsjLbl)
                .addGap(22, 22, 22)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreGTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreGLbl))
                .addGap(27, 27, 27)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoGLbl)
                    .addComponent(tipoGCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaIDCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaILbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validFechIniLbl)
                .addGap(19, 19, 19)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaTLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaTDCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sedeGLbl)
                    .addComponent(tipoSedeGCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validSedeLbl)
                .addGap(19, 19, 19)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePrLbl)
                    .addComponent(nombreGCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validProveedorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(generalPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        informacionTBn.addTab("General", generalPnl);

        listaAsistenciaMsjLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaAsistenciaMsjLbl.setText("Seleccione la opcion de generar lista de asistencia para agregar los empleados que desee que asistan al evento");

        listaAsistenciaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero del empleado", "Nombre del empleado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaAsistenciaTbl.setEnabled(false);
        listaAsistenciaSPn.setViewportView(listaAsistenciaTbl);
        if (listaAsistenciaTbl.getColumnModel().getColumnCount() > 0) {
            listaAsistenciaTbl.getColumnModel().getColumn(0).setResizable(false);
            listaAsistenciaTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        siguienteLABtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siguienteLABtn.setText("Siguiente");
        siguienteLABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteLABtnActionPerformed(evt);
            }
        });

        listaAsistenciaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listaAsistenciaLbl.setText("Lista de asistencia");

        registroMsjLbl.setText("Ingrese la información a almacenar, para salir o cancelar el registro presione el botón \"Cancelar\"");

        generarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generarBtn.setText("Generar lista de asistencia");
        generarBtn.setAutoscrolls(true);
        generarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtnActionPerformed(evt);
            }
        });

        registroLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registroLbl.setText("Registro");

        cancelarLABtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarLABtn.setText("Cancelar");
        cancelarLABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarLABtnActionPerformed(evt);
            }
        });

        regresarLABtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regresarLABtn.setText("Regresar");
        regresarLABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarLABtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listaPnlLayout = new javax.swing.GroupLayout(listaPnl);
        listaPnl.setLayout(listaPnlLayout);
        listaPnlLayout.setHorizontalGroup(
            listaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresarLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelarLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siguienteLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaAsistenciaLbl)
                .addGap(315, 315, 315))
            .addGroup(listaPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(listaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaAsistenciaSPn, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registroLbl)
                    .addComponent(registroMsjLbl)
                    .addComponent(listaAsistenciaMsjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarBtn))
                .addGap(55, 55, 55))
        );
        listaPnlLayout.setVerticalGroup(
            listaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(registroLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registroMsjLbl)
                .addGap(18, 18, 18)
                .addComponent(listaAsistenciaMsjLbl)
                .addGroup(listaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(generarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(listaAsistenciaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaAsistenciaSPn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(listaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siguienteLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regresarLABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        informacionTBn.addTab("Lista de asistencia", null, listaPnl, "");

        guardarCBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarCBtn.setText("Guardar");
        guardarCBtn.setEnabled(false);
        guardarCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCBtnActionPerformed(evt);
            }
        });

        enunciadoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Enunciado", "Calificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enunciadoTbl.setEnabled(false);
        enunciadoSPn.setViewportView(enunciadoTbl);
        if (enunciadoTbl.getColumnModel().getColumnCount() > 0) {
            enunciadoTbl.getColumnModel().getColumn(0).setResizable(false);
            enunciadoTbl.getColumnModel().getColumn(1).setResizable(false);
            enunciadoTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        calificacionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calificacionLbl.setText("Registro");

        calificacionMsjLbl.setText("Ingrese la información a almacenar, para salir o cancelar el registro presione el botón \"Cancelar\"");

        cancelarCBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarCBtn.setText("Cancelar");
        cancelarCBtn.setEnabled(false);
        cancelarCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCBtnActionPerformed(evt);
            }
        });

        regresarCBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regresarCBtn.setText("Regresar");
        regresarCBtn.setEnabled(false);
        regresarCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarCBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calificacionPnlLayout = new javax.swing.GroupLayout(calificacionPnl);
        calificacionPnl.setLayout(calificacionPnlLayout);
        calificacionPnlLayout.setHorizontalGroup(
            calificacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calificacionPnlLayout.createSequentialGroup()
                .addGroup(calificacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(calificacionPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regresarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(calificacionPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enunciadoSPn, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(calificacionPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(calificacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calificacionMsjLbl)
                    .addComponent(calificacionLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calificacionPnlLayout.setVerticalGroup(
            calificacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calificacionPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(calificacionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calificacionMsjLbl)
                .addGap(18, 18, 18)
                .addComponent(enunciadoSPn, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(calificacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        informacionTBn.addTab("Calificación de logística ", calificacionPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionTBn, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionTBn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento ejecutado al hacer click se buscara al empleado dependiendo de del
     * campo seleccionado
     *
     * @param evt Evento al presionar el boton
     */
    private void generarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtnActionPerformed
        ListaAsistenciaFrm lista = new ListaAsistenciaFrm(this);
        lista.setVisible(true);
        capacisoft.setEnabled(false);
        String[][] matriz = new String[modelTablaEmF.
                getRowCount()][modelTablaEmF.getColumnCount()];
        for (int k = 0; k < modelTablaEmF.getRowCount(); k++) {
            for (int j = 0; j < modelTablaEmF.getColumnCount(); j++) {
                matriz[k][j] = modelTablaEmF.getValueAt(k, j) + "";
            }
        }
        if (listaAsistenciaTbl.getRowCount() > 0) {
            lista.mandarTabla(matriz);
        }
    }//GEN-LAST:event_generarBtnActionPerformed
    /**
     * Evento ejecutado al hacer click mandando a un metodo que guarde la
     * informacion o la modificque.
     *
     * @param evt Evento al presionar el boton
     */
    private void siguienteLABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteLABtnActionPerformed
        informacionTBn.setEnabledAt(0, false);
        informacionTBn.setEnabledAt(1, false);
        informacionTBn.setEnabledAt(2, true);
        informacionTBn.setSelectedIndex(2);
    }//GEN-LAST:event_siguienteLABtnActionPerformed
    /**
     * Evento ejecutado al hacer click mandando a un metodo que guarde la
     * informacion o la modificque.
     *
     * @param evt Evento al presionar el boton
     */
    private void guardarCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCBtnActionPerformed
        guarMod();
    }//GEN-LAST:event_guardarCBtnActionPerformed
    /**
     * Evento ejecutado al hacer click mandando a un metodo que guarde la
     * informacion o la modificque.
     *
     * @param evt Evento al presionar el boton
     */
    private void siguienteGBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteGBtnActionPerformed
        informacionTBn.setEnabledAt(0, false);
        informacionTBn.setEnabledAt(1, true);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(1);
    }//GEN-LAST:event_siguienteGBtnActionPerformed

    /**
     * Este metodo sirve para cancelar el registro o la modificacion de un
     * evento
     *
     * @param evt
     */
    private void cancelarGBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarGBtnActionPerformed
        cancelar();
    }//GEN-LAST:event_cancelarGBtnActionPerformed
    /**
     * Este metodo sirve para cancelar el registro o la modificacion de un
     * evento
     *
     * @param evt
     */
    private void cancelarLABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarLABtnActionPerformed
        cancelar();
    }//GEN-LAST:event_cancelarLABtnActionPerformed
    /**
     * Este metodo sirve para cancelar el registro o la modificacion de un
     * evento
     *
     * @param evt
     */
    private void cancelarCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCBtnActionPerformed
        cancelar();
    }//GEN-LAST:event_cancelarCBtnActionPerformed

    /**
     * Este metodo sirve para cancelar el proceso de registro o modificacion de
     * un evento
     */
    private void cancelar() {
        int opcion;
        if (guardarCBtn.getText().equals("Guardar")) {
            opcion = JOptionPane.showConfirmDialog(this, "¿Desea cancelar el "
                    + "registro del evento?", "Precaucion",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        } else {
            opcion = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la "
                    + "modificacion del evento?", "Precaucion",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        if (opcion == 0) {
            this.setVisible(false);
            limpiarCampos();
        }
    }

    /**
     * Metodo para indicar que a habido un cambio en la el panel
     *
     * @param evt
     */
    private void tipoSedeGCBxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoSedeGCBxItemStateChanged
        if ((Sede) tipoSedeGCBx.getSelectedItem() != null) {
            if (tipoSedeGCBx.getSelectedItem().toString().compareTo("") != 0) {
                this.cambio = true;
            }
        }
    }//GEN-LAST:event_tipoSedeGCBxItemStateChanged
    /**
     * Metodo para indicar que a habido un cambio en el panel
     *
     * @param evt
     */
    private void nombreGCBxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreGCBxItemStateChanged
        if ((Proveedor) nombreGCBx.getSelectedItem() != null) {
            if (((Proveedor) nombreGCBx.getSelectedItem()).getId() != null) {
                this.cambio = true;
            }
        }
    }//GEN-LAST:event_nombreGCBxItemStateChanged

    private void regresarLABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarLABtnActionPerformed
        informacionTBn.setEnabledAt(0, true);
        informacionTBn.setEnabledAt(1, false);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(0);
    }//GEN-LAST:event_regresarLABtnActionPerformed

    private void regresarCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarCBtnActionPerformed
        informacionTBn.setEnabledAt(0, false);
        informacionTBn.setEnabledAt(1, true);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(1);
    }//GEN-LAST:event_regresarCBtnActionPerformed
    /**
     * Metodo que permite mandar a obtener la informacion de todos las sedes y
     * proveedores registrados informacion o la modificque.
     *
     * @param evt Evento al presionar el boton
     */
    public void llenarTodo() {
        tabla();
        control.setClass(Sede.class);
        control.buscarTodosLista(1);
        control.setClass(Proveedor.class);
        control.buscarTodosLista(2);
        control.setClass(EnunciadoLogistica.class);
        control.buscarEncuesta();
        cambio = false;
        informacionTBn.setEnabledAt(0, true);
        informacionTBn.setEnabledAt(1, false);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(0);
    }

    /**
     * Metodo que recibe el evento del catalogo para llenar parte de la
     * informacion general del evento a llevar a cabo
     *
     * @param evento
     */
    public void llenarEvento(Evento evento) {
        this.evento = evento;
        generalLbl.setText("Agregar evento a realizar");
        registroLbl.setText("Agregar evento a realizar");
        guardarCBtn.setText("Guardar");
        nombreGTFd.setText(evento.getNombre());
        if (evento.getTipoEvento().equals("CONFERENCIA")) {
            tipoGCBx.setSelectedIndex(0);
        } else if (evento.getTipoEvento().equals("TALLER")) {
            tipoGCBx.setSelectedIndex(1);
        } else if (evento.getTipoEvento().equals("CURSO")) {
            tipoGCBx.setSelectedIndex(2);
        } else if (evento.getTipoEvento().equals("CURSO / TALLER")) {
            tipoGCBx.setSelectedIndex(3);
        } else if (evento.getTipoEvento().equals("PLATICA")) {
            tipoGCBx.setSelectedIndex(4);
        }
        control.setClass(Sede.class);
        control.buscarTodosLista(1);
        control.setClass(Proveedor.class);
        control.buscarTodosLista(2);
        control.setClass(EnunciadoLogistica.class);
        control.buscarEncuesta();
        cambio = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calificacionLbl;
    private javax.swing.JLabel calificacionMsjLbl;
    private javax.swing.JPanel calificacionPnl;
    private javax.swing.JButton cancelarCBtn;
    private javax.swing.JButton cancelarGBtn;
    private javax.swing.JButton cancelarLABtn;
    private javax.swing.JScrollPane enunciadoSPn;
    private javax.swing.JTable enunciadoTbl;
    private com.toedter.calendar.JDateChooser fechaIDCh;
    private javax.swing.JLabel fechaILbl;
    private com.toedter.calendar.JDateChooser fechaTDCh;
    private javax.swing.JLabel fechaTLbl;
    private javax.swing.JLabel generalLbl;
    private javax.swing.JLabel generalMsjLbl;
    private javax.swing.JPanel generalPnl;
    private javax.swing.JButton generarBtn;
    private javax.swing.JButton guardarCBtn;
    private javax.swing.JTabbedPane informacionTBn;
    private javax.swing.JLabel listaAsistenciaLbl;
    private javax.swing.JLabel listaAsistenciaMsjLbl;
    private javax.swing.JScrollPane listaAsistenciaSPn;
    private javax.swing.JTable listaAsistenciaTbl;
    private javax.swing.JPanel listaPnl;
    private javax.swing.JComboBox nombreGCBx;
    private javax.swing.JLabel nombreGLbl;
    private javax.swing.JTextField nombreGTFd;
    private javax.swing.JLabel nombrePrLbl;
    private javax.swing.JLabel registroLbl;
    private javax.swing.JLabel registroMsjLbl;
    private javax.swing.JButton regresarCBtn;
    private javax.swing.JButton regresarLABtn;
    private javax.swing.JLabel sedeGLbl;
    private javax.swing.JButton siguienteGBtn;
    private javax.swing.JButton siguienteLABtn;
    private javax.swing.JComboBox tipoGCBx;
    private javax.swing.JLabel tipoGLbl;
    private javax.swing.JComboBox tipoSedeGCBx;
    private javax.swing.JLabel validFechIniLbl;
    private javax.swing.JLabel validProveedorLbl;
    private javax.swing.JLabel validSedeLbl;
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo sobrescrito de la clase comunicador mensaje de confirmación de
     * registro o modificacion exitosa.
     *
     * @param mensaje String con mensaje de confirmacion de registro.
     */
    @Override
    public void setMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * Metodo que recibe una matriz, donde se obtendran sus valores para
     * añadirlos a la modelo de la tabla, también se ocultara la columna id y se
     * le dara se redefinira el ancho de la columna 0.
     *
     * @param info Matriz String para vaciar en tabla
     */
    @Override
    public void setTabla(String[][] info) {
        if (info == null) {
            Object[][] tableData = new Object[enunciadoTbl.
                    getRowCount()][enunciadoTbl.getColumnCount() + 1];
            for (int i = 0; i < enunciadoTbl.getRowCount(); i++) {
                tableData[i][0] = modelTablaEn.getValueAt(i, 0);
                tableData[i][1] = modelTablaEn.getValueAt(i, 1);
                tableData[i][2] = modelTablaEn.getValueAt(i, 2);
                tableData[i][3] = "";
            }

            enunciadoTbl.setEnabled(true);
            modelTablaEn.setDataVector(tableData, titulosTablaEn);
            //Contador que decrementa del 10 a 1 para agregarlos a la
            //califiacion de logistica
            JComboBox comboBox = new JComboBox();
            for (int numero = 10; numero > 0; numero--) {
                comboBox.addItem(numero + "");
            }
            TableColumn tc = enunciadoTbl.getColumnModel().getColumn(3);
            tc.setCellEditor(new DefaultCellEditor(comboBox));
            DefaultTableCellRenderer renderer
                    = new DefaultTableCellRenderer();
            renderer.setToolTipText("Califica a la logistica");
            tc.setCellRenderer(renderer);
            tc = enunciadoTbl.getColumnModel().getColumn(0);
            enunciadoTbl.getColumnModel().removeColumn(tc);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            enunciadoTbl.getColumnModel().getColumn(0).setPreferredWidth(600);
            enunciadoTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            enunciadoTbl.getColumnModel().getColumn(2).setPreferredWidth(200);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        } else if (info[0][0].contains("TLE1")) {
            info[0][0] = info[0][0].replaceAll("TLE1", "");
            modelTablaEmF.setDataVector(info, titulosTablaEm);
        } else if (info[0][0].contains(
                "TLE3")) {
            //Se checa si la palabra TLE3 se encuentra dentro de la matriz
            info[0][0] = info[0][0].replaceAll("TLE3", "");
            //Se elimina la palabra TLE3 para que solo quede el id puro
            enunciadoTbl.setEnabled(true);
            modelTablaEn.setDataVector(info, titulosTablaEn);
            //Contador que decrementa del 10 a 1 para agregarlos a la
            //califiacion de logistica
            JComboBox comboBox = new JComboBox();
            for (int numero = 10; numero > 0; numero--) {
                comboBox.addItem(numero + "");
            }
            TableColumn tc = enunciadoTbl.getColumnModel().getColumn(3);
            tc.setCellEditor(new DefaultCellEditor(comboBox));
            DefaultTableCellRenderer renderer
                    = new DefaultTableCellRenderer();
            renderer.setToolTipText("Califica a la logistica");
            tc.setCellRenderer(renderer);
            tc = enunciadoTbl.getColumnModel().getColumn(0);
            enunciadoTbl.getColumnModel().removeColumn(tc);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            enunciadoTbl.getColumnModel().getColumn(0).setPreferredWidth(600);
            enunciadoTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            enunciadoTbl.getColumnModel().getColumn(2).setPreferredWidth(200);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        } else if (info[0][0].contains(
                "TLE4")) {
            //Se checa si la palabra TLE4 se encuentra dentro de la matriz
            info[0][0] = info[0][0].replaceAll("TLE4", "");
            //Se elimina la palabra TLE4 para que solo quede el id puro

            Object[][] tableData = new Object[enunciadoTbl.
                    getRowCount()][enunciadoTbl.getColumnCount() + 1];
            for (int i = 0; i < enunciadoTbl.getRowCount(); i++) {
                tableData[i][0] = info[i][0];
                tableData[i][1] = modelTablaEn.getValueAt(i, 1);
                tableData[i][2] = modelTablaEn.getValueAt(i, 2);
                tableData[i][3] = info[i][3];
            }

            enunciadoTbl.setEnabled(true);
            modelTablaEn.setDataVector(tableData, titulosTablaEn);
            //Contador que decrementa del 10 a 1 para agregarlos a la
            //califiacion de logistica
            JComboBox comboBox = new JComboBox();
            for (int numero = 10; numero > 0; numero--) {
                comboBox.addItem(numero + "");
            }
            TableColumn tc = enunciadoTbl.getColumnModel().getColumn(3);
            tc.setCellEditor(new DefaultCellEditor(comboBox));
            DefaultTableCellRenderer renderer
                    = new DefaultTableCellRenderer();
            renderer.setToolTipText("Califica a la logistica");
            tc.setCellRenderer(renderer);
            tc = enunciadoTbl.getColumnModel().getColumn(0);
            enunciadoTbl.getColumnModel().removeColumn(tc);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            enunciadoTbl.getColumnModel().getColumn(0).setPreferredWidth(600);
            enunciadoTbl.getColumnModel().getColumn(1).setPreferredWidth(200);
            enunciadoTbl.getColumnModel().getColumn(2).setPreferredWidth(200);
            enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        }
    }

    /**
     * Metodo sobrescrito de la clase Comunicador
     *
     * @param info
     * @param i
     */
    @Override
    public void setInfo(List info) {
        if (info.get(0).equals("Desbloquear")) {
            capacisoft.setEnabled(true);
            capacisoft.setVisible(true);
        }
    }

    /**
     * Agrega los datos al modelo de la tabla, también se ocultara la columna id
     * y se le dara se redefinira el ancho de la columna 0.
     *
     * @param info
     */
    private void tabla() {

        modelTablaEmF.setDataVector(null, titulosTablaEm);

        listaAsistenciaTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        listaAsistenciaTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        listaAsistenciaTbl.getColumnModel().getColumn(1).setPreferredWidth(160);
        listaAsistenciaTbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        modelTablaEn.setDataVector(null, titulosTablaEn);
        TableColumn tc = enunciadoTbl.getColumnModel().getColumn(0);
        enunciadoTbl.getColumnModel().removeColumn(tc);
        enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        enunciadoTbl.getColumnModel().getColumn(0).setPreferredWidth(1200);
        enunciadoTbl.getColumnModel().getColumn(1).setPreferredWidth(50);
        enunciadoTbl.getColumnModel().getColumn(2).setPreferredWidth(50);
        enunciadoTbl.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

    }

    /**
     * Metodo sobrescrito de la clase comunicador que recibe una Lista con la
     * los resultados de una busqueda especifica y vaciarlo en los campos y
     * checkbox
     *
     * @param info Lista de Objeto con información de búsqueda.
     */
    @Override
    public void setLista(List info, int i) {
        if (info.isEmpty()) {
            return;
        }
        switch (i) {
            case 1:
                sedeModel.removeAllElements();
                sedeModel.addElement(new Sede(""));
                for (Object j : info) {
                    sedeModel.addElement(j);
                }
                break;
            case 2:
                proveedorModel.removeAllElements();
                proveedorModel.addElement(new Proveedor("", "", "", ""));
                for (Object j : info) {
                    proveedorModel.addElement(j);
                }
                break;
        }
    }

    /**
     * Establece una visibilidad de las opciones del panel del usuario
     *
     * @param visibilidad
     */
    public void visibilidad(boolean visibilidad) {
        fechaIDCh.setEnabled(visibilidad);
        fechaTDCh.setEnabled(visibilidad);
        tipoSedeGCBx.setEnabled(visibilidad);
        nombreGCBx.setEnabled(visibilidad);
        siguienteGBtn.setEnabled(visibilidad);
        cancelarGBtn.setEnabled(visibilidad);
        siguienteLABtn.setEnabled(visibilidad);
        cancelarLABtn.setEnabled(visibilidad);
        enunciadoTbl.setEnabled(visibilidad);
        guardarCBtn.setEnabled(visibilidad);
        cancelarCBtn.setEnabled(visibilidad);
        regresarLABtn.setEnabled(visibilidad);
        regresarCBtn.setEnabled(visibilidad);
    }

    /**
     * Establece una opcion para guardar o modificar la informacion para
     * mandarla a la base de datos
     *
     * @param visibilidad
     */
    private void guarMod() {
        HashSet<Empleado> lisEmpleado = new HashSet();
        List<Object> eventoImplementar = new ArrayList();
        List<Object> calificacion = new ArrayList();
        ImplementacionEvento implementacionEvento = new ImplementacionEvento();

        if (validacion() == false) {
            if (fechaTDCh.getDate() == null) {
                fechaTDCh.setDate(fechaIDCh.getDate());
            }
            if (guardarCBtn.getText().equals("Modificar")) {
                eventoImplementar.add(eventoProgramarId);
            }
            eventoImplementar.add(evento);
            eventoImplementar.add(fechaIDCh.getDate());
            eventoImplementar.add(fechaTDCh.getDate());
            eventoImplementar.add(false);
            eventoImplementar.add(tipoSedeGCBx.getSelectedItem());
            eventoImplementar.add(nombreGCBx.getSelectedItem());
            for (int x = 0; x < listaAsistenciaTbl.getRowCount(); x++) {
                Empleado empleado = new Empleado();
                empleado.setNumero((String) modelTablaEmF.getValueAt(x, 0));
                lisEmpleado.add(empleado);
            }
            eventoImplementar.add(lisEmpleado);
            for (int x = 0; x < enunciadoTbl.getRowCount(); x++) {
                ImplementacionEventoEnunciadoLogistica calificacionLog
                        = new ImplementacionEventoEnunciadoLogistica();
                EnunciadoLogistica enunciado = new EnunciadoLogistica();
                ImplementacionEvento evento = new ImplementacionEvento();
                enunciado.setId(x + 1);
                calificacionLog.setEnunciadoLogistica(enunciado);
                calificacionLog.setCalificacion(Integer.
                        parseInt((String) modelTablaEn.
                                getValueAt(x, 3)));
                if (guardarCBtn.getText().equals("Modificar")) {
                    calificacionLog.setId(Integer.
                            parseInt((String) modelTablaEn.
                                    getValueAt(x, 0)));
                    evento.setId(eventoProgramarId);
                    calificacionLog.setImplementacionEvento(evento);
                }
                calificacion.add(calificacionLog);
            }
            control.setClass(ImplementacionEvento.class);
            if (guardarCBtn.getText().equals("Guardar")) {
                implementacionEvento = DataHelper.
                        getImplementarEvento(eventoImplementar, "Guardar");
                control.guardarOModificarEventoImplementado(implementacionEvento,
                        calificacion, "Guardar");
            } else {
                implementacionEvento = DataHelper.
                        getImplementarEvento(eventoImplementar, "Modificar");
                control.guardarOModificarEventoImplementado(implementacionEvento,
                        calificacion, "Modificar");
            }
            limpiarCampos();
            this.cambio = false;
        }
    }

    /**
     * Este metodo obtiene la informacion del evento a realizar del
     * PnlProgramarEvento para que este la pueda modificar
     *
     * @param info
     */
    public void obtenerMod(List info) {
        ImplementacionEvento eventoImplementado = new ImplementacionEvento();
        generalLbl.setText("Modificar evento realizado");
        registroLbl.setText("Modificar evento realizado");
        calificacionLbl.setText("Modificar evento realizado");
        guardarCBtn.setText("Modificar");
        eventoProgramarId = Integer.parseInt(info.get(0).toString());
        evento = (Evento) info.get(1);
        nombreGTFd.setText(info.get(2).toString());
        if (info.get(4).equals("CONFERENCIA")) {
            tipoGCBx.setSelectedIndex(0);
        } else if (info.get(4).equals("TALLER")) {
            tipoGCBx.setSelectedIndex(1);
        } else if (info.get(4).equals("CURSO")) {
            tipoGCBx.setSelectedIndex(2);
        } else if (info.get(4).equals("CURSO / TALLER")) {
            tipoGCBx.setSelectedIndex(3);
        } else if (info.get(4).equals("PLATICA")) {
            tipoGCBx.setSelectedIndex(4);
        }
        fechaIDCh.setDate((Date) info.get(5));
        fechaTDCh.setDate((Date) info.get(6));
        sedeModel.setSelectedItem(info.get(7));
        proveedorModel.setSelectedItem(info.get(8));
        eventoImplementado.setEmpleados((Set<Empleado>) info.get(9));
        Iterator itr = eventoImplementado.getEmpleados().iterator();
        eventoImplementado.setId(eventoProgramarId);
        Object[][] tableData = new Object[eventoImplementado.getEmpleados().
                size()][modelTablaEmF.getColumnCount()];
        for (int x = 0; x < eventoImplementado.getEmpleados().size(); x++) {
            Empleado empleado = (Empleado) itr.next();
            tableData[x][0] = empleado.getNumero() + "";
            if (empleado.getSegundoNombre() == null) {
                tableData[x][1] = empleado.getPrimerNombre() + " "
                        + empleado.getApellidoPaterno() + " " + empleado.
                        getApellidoMaterno();

            } else {
                tableData[x][1] = empleado.getPrimerNombre() + " "
                        + empleado.getSegundoNombre() + " " + empleado.
                        getApellidoPaterno() + " " + empleado.
                        getApellidoMaterno();

            }
        }
        modelTablaEmF.setDataVector(tableData, titulosTablaEm);
        informacionTBn.setSelectedIndex(0);
        control.setClass(ImplementacionEventoEnunciadoLogistica.class);
        control.bucarCalificacionMod(eventoImplementado);
        informacionTBn.setEnabledAt(0, true);
        informacionTBn.setEnabledAt(1, false);
        informacionTBn.setEnabledAt(2, false);
        informacionTBn.setSelectedIndex(0);
        listaAsistenciaTbl.setEnabled(true);

    }

    /**
     * Metodo que regresa un true si se encontraron informacion sin completar, o
     * errores en la informacion, como es mostrado en el caso de prueba
     *
     * @return
     */
    private boolean validacion() {
        if (fechaIDCh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "No lleno el campo de la fecha"
                    + " inicial");
            return true;
        } else if (tipoSedeGCBx.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "No selecciono una sede");
            return true;
        } else if (((Proveedor) nombreGCBx.getSelectedItem()).getId() == null) {
            JOptionPane.showMessageDialog(this, "No selecciono un proveedor");
            return true;
        } else if (listaAsistenciaTbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron empleados"
                    + " en la lista de asistencia");
            return true;
        } else if (fechaTDCh.getDate() != null) {
            if (fechaIDCh.getDate().after(fechaTDCh.getDate())) {
                JOptionPane.showMessageDialog(this, "Error en las fechas de"
                        + " evento. La fecha de inicio es mayor que la fecha de"
                        + " terminacion");
                return true;
            }
        }
        if (guardarCBtn.getText().equals("Guardar")) {
            for (int i = 0; i < enunciadoTbl.getRowCount(); i++) {
                if (((Object) modelTablaEn.getValueAt(i, 3)) == null) {
                    JOptionPane.showMessageDialog(this, "No se a completado la "
                            + "calificacion de la logistica");
                    return true;
                }
            }
        } else {
            for (int i = 0; i < enunciadoTbl.getRowCount(); i++) {
                try {
                    Integer cal = Integer.parseInt((String) modelTablaEn.getValueAt(i, 3));
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "No se a completado la "
                            + "calificacion de la logistica");
                    return true;
                }
            }
        }
        return false;

    }

    /**
     * Este metodo sirve para limpiar los campos del panel de evento
     */
    public void limpiarCampos() {
        this.cambio = false;
        this.setVisible(false);
        fechaIDCh.setDate(null);
        fechaTDCh.setDate(null);
        tabla();
    }

    /**
     * Variable que regresa un booleano si se le agrego informacion al evento o
     * modifico
     *
     * @return regresa un booleano que indica si el evento sufrio cambios
     */
    public boolean isCambio() {
        return this.cambio;
    }

    @Override
    public void llenarDatos(Object implementacionEvento) {
    }

    /**
     * Este metodo detecta que el usuario esta modificando un campo y hace el
     * label de recordatorio invisible
     *
     * @param e
     */
    @Override
    public void focusGained(FocusEvent e) {
        Object fuente = e.getSource();
        if (fuente == fechaIDCh) {

        } else if (fuente == tipoSedeGCBx) {
            validSedeLbl.setVisible(false);
        } else if (fuente == nombreGCBx) {
            validProveedorLbl.setVisible(false);
        }
    }

    /**
     * Este metodo detecta que el usuario perdio el foco de un campo y no
     * escribio nada en el avisandole que el campo es obligatorio
     *
     * @param e
     */
    @Override
    public void focusLost(FocusEvent e) {
        Object fuente = e.getSource();
        if (fuente == fechaIDCh) {

        } else if (fuente == tipoSedeGCBx) {
            if (tipoSedeGCBx.getSelectedItem().toString().equals("")) {
                validSedeLbl.setVisible(true);
            }
        } else if (fuente == nombreGCBx) {
            if (((Proveedor) nombreGCBx.getSelectedItem()).getId() == null) {
                validProveedorLbl.setVisible(true);
            }
        }
    }
}
