/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.cobach.vista;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import mx.edu.cobach.persistencia.entidades.Adscripcion;
import mx.edu.cobach.persistencia.entidades.Departamento;
import mx.edu.cobach.persistencia.entidades.Direccion;
import mx.edu.cobach.persistencia.entidades.Empleado;
import mx.edu.cobach.persistencia.entidades.Plantel;
import mx.edu.cobach.persistencia.entidades.Puesto;
import mx.edu.cobach.vista.controlador.EmpleadoControlador;
import mx.edu.cobach.vista.controlador.HelperEntidad;

/**
 *
 * @author Fernando
 */
public class PnlEmpleadoAdministrativo extends javax.swing.JPanel implements
        Comunicador, FocusListener {

    private final DefaultTableModel model;
    private final DefaultComboBoxModel puestoModel, plantelModel, dptoModel,
            adscripModel, dirModel;
    private final String[] titulosTabla;
    private final EmpleadoControlador control;
    private int idEmpleadoActual;
    private final Border BORDER_ORIGINAL;

    /**
     * Constructor del PnlEmpleadoAdministrativo
     */
    public PnlEmpleadoAdministrativo() {
        this.titulosTabla = new String[]{"ID", "Numero", "Nombre", "Eliminar"};
        initComponents();
        model = new DefaultTableModel(titulosTabla, 5) {
            @Override
            public boolean isCellEditable(int row, int col) {
                if (col == 3) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        tablaTbl.setModel(model);
        tablaTbl.setColumnSelectionAllowed(false);
        tablaTbl.setDragEnabled(false);
        control = new EmpleadoControlador(this, Empleado.class);
        puestoModel = new DefaultComboBoxModel();
        plantelModel = new DefaultComboBoxModel();
        dptoModel = new DefaultComboBoxModel();
        adscripModel = new DefaultComboBoxModel();
        dirModel = new DefaultComboBoxModel();
        puestoCBx.setModel(puestoModel);
        plantelCBx.setModel(plantelModel);
        departamentoCBx.setModel(dptoModel);
        adscCBx.setModel(adscripModel);
        adscBuscarCBx.setModel(adscripModel);
        direccionCBx.setModel(dirModel);
        numeroTFd.addFocusListener(this);
        primerNombreTFd.addFocusListener(this);
        primerApellidoTFd.addFocusListener(this);
        correoTFd.addFocusListener(this);
        BORDER_ORIGINAL = numeroTFd.getBorder();
        informacionJTP.setEnabledAt(0, true);
        informacionJTP.setEnabledAt(1, false);
        informacionJTP.setSelectedIndex(0);
        control.buscarTodos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionPnl = new javax.swing.JPanel();
        nombreBuscarLbl = new javax.swing.JLabel();
        adscBuscarLbl = new javax.swing.JLabel();
        nombreBuscarTFd = new javax.swing.JTextField();
        tablaSPn = new javax.swing.JScrollPane();
        tablaTbl = new javax.swing.JTable();
        buscarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        adscBuscarCBx = new javax.swing.JComboBox();
        opcionMsjLbl = new javax.swing.JLabel();
        opcionLbl = new javax.swing.JLabel();
        tablaMsjLbl = new javax.swing.JLabel();
        informacionJTP = new javax.swing.JTabbedPane();
        informacion1Pnl = new javax.swing.JPanel();
        numeroLbl = new javax.swing.JLabel();
        correoELbl = new javax.swing.JLabel();
        numeroTFd = new javax.swing.JTextField();
        correoTFd = new javax.swing.JTextField();
        primerNombreLbl = new javax.swing.JLabel();
        primerNombreTFd = new javax.swing.JTextField();
        segNombreTFd = new javax.swing.JTextField();
        segNombreLbl = new javax.swing.JLabel();
        segApellidoTFd = new javax.swing.JTextField();
        segApellidoLbl = new javax.swing.JLabel();
        primerApellidoTFd = new javax.swing.JTextField();
        primerApellidoLbl = new javax.swing.JLabel();
        registroLbl = new javax.swing.JLabel();
        registroMsjLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        validNumLbl = new javax.swing.JLabel();
        validNombLbl = new javax.swing.JLabel();
        validApellLbl = new javax.swing.JLabel();
        validCorreo_Lbl = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        siguienteBtn = new javax.swing.JButton();
        informacion2Pnl = new javax.swing.JPanel();
        puestoCBx = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        puestoLbll = new javax.swing.JLabel();
        adscLbl = new javax.swing.JLabel();
        direccionLbl = new javax.swing.JLabel();
        plantelCBx = new javax.swing.JComboBox();
        adscCBx = new javax.swing.JComboBox();
        departamentoCBx = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        plantelLbl = new javax.swing.JLabel();
        cancelarBtn2 = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();
        departamentoLbl1 = new javax.swing.JLabel();
        direccionCBx = new javax.swing.JComboBox();
        regresarBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        opcionPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        opcionPnl.setMaximumSize(new java.awt.Dimension(408, 587));
        opcionPnl.setMinimumSize(new java.awt.Dimension(408, 587));
        opcionPnl.setPreferredSize(new java.awt.Dimension(408, 587));

        nombreBuscarLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBuscarLbl.setText("Nombre del empledo:");

        adscBuscarLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adscBuscarLbl.setText("Adscripción del empleado:");

        nombreBuscarTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreBuscarTFd.setEnabled(false);

        tablaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTblMouseClicked(evt);
            }
        });
        tablaSPn.setViewportView(tablaTbl);
        if (tablaTbl.getColumnModel().getColumnCount() > 0) {
            tablaTbl.getColumnModel().getColumn(0).setResizable(false);
            tablaTbl.getColumnModel().getColumn(1).setResizable(false);
            tablaTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        agregarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        adscBuscarCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adscBuscarCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Todos", "Plantel", "Departamento" }));
        adscBuscarCBx.setEnabled(false);

        opcionMsjLbl.setText("<html>Seleccione el botón \"Agregar\" para habilitar la sección de registro,<br>si desea  realizar una búsqueda seleccione el botón \"Buscar\"</html>");

        opcionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcionLbl.setText("Opciones ");

        tablaMsjLbl.setText("<html>Para Modificar seleccione un número del empleado de la columna<br> \"Numero\", para eliminar selecciona el cuadro eliminar de la columna Eliminar del empleado que desee</html> ");

        javax.swing.GroupLayout opcionPnlLayout = new javax.swing.GroupLayout(opcionPnl);
        opcionPnl.setLayout(opcionPnlLayout);
        opcionPnlLayout.setHorizontalGroup(
            opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionPnlLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(opcionPnlLayout.createSequentialGroup()
                                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agregarBtn)
                                    .addComponent(adscBuscarLbl)
                                    .addComponent(nombreBuscarLbl))
                                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(opcionPnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(opcionPnlLayout.createSequentialGroup()
                                                .addComponent(nombreBuscarTFd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(opcionPnlLayout.createSequentialGroup()
                                                .addComponent(adscBuscarCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(61, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionPnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))))
                            .addGroup(opcionPnlLayout.createSequentialGroup()
                                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionLbl)
                                    .addComponent(opcionMsjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(opcionPnlLayout.createSequentialGroup()
                        .addComponent(tablaSPn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(tablaMsjLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
        );
        opcionPnlLayout.setVerticalGroup(
            opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionMsjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreBuscarTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreBuscarLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adscBuscarLbl)
                    .addComponent(adscBuscarCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBtn)
                    .addComponent(buscarBtn))
                .addGap(13, 13, 13)
                .addComponent(tablaMsjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaSPn, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informacion1Pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        numeroLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroLbl.setText("Num. Empleado:");

        correoELbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correoELbl.setText("Correo electrónico :");

        numeroTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroTFd.setEnabled(false);
        numeroTFd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroTFdKeyTyped(evt);
            }
        });

        correoTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correoTFd.setEnabled(false);
        correoTFd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoTFdKeyTyped(evt);
            }
        });

        primerNombreLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        primerNombreLbl.setText("Primer nombre:");

        primerNombreTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        primerNombreTFd.setEnabled(false);
        primerNombreTFd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                primerNombreTFdKeyTyped(evt);
            }
        });

        segNombreTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        segNombreTFd.setEnabled(false);

        segNombreLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        segNombreLbl.setText("Segundo nombre:");

        segApellidoTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        segApellidoTFd.setEnabled(false);

        segApellidoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        segApellidoLbl.setText("Segundo apellido:");

        primerApellidoTFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        primerApellidoTFd.setEnabled(false);
        primerApellidoTFd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                primerApellidoTFdKeyTyped(evt);
            }
        });

        primerApellidoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        primerApellidoLbl.setText("Primer apellido:");

        registroLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registroLbl.setText("Registro");

        registroMsjLbl.setText("Ingrese la información a almacenar, para salir o cancelar el registro presione el botón Cancelar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("@cobachbc.edu.mx");

        validNumLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        validNumLbl.setForeground(new java.awt.Color(213, 216, 222));
        validNumLbl.setText("Este campo es obligatorio");

        validNombLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        validNombLbl.setForeground(new java.awt.Color(213, 216, 222));
        validNombLbl.setText("Este campo es obligatorio");

        validApellLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        validApellLbl.setForeground(new java.awt.Color(213, 216, 222));
        validApellLbl.setText("Este campo es obligatorio");

        validCorreo_Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        validCorreo_Lbl.setForeground(new java.awt.Color(213, 216, 222));
        validCorreo_Lbl.setText("Este campo es obligatorio");

        cancelarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarBtn.setText("Cancelar");
        cancelarBtn.setEnabled(false);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        siguienteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siguienteBtn.setText("Siguiente");
        siguienteBtn.setEnabled(false);
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informacion1PnlLayout = new javax.swing.GroupLayout(informacion1Pnl);
        informacion1Pnl.setLayout(informacion1PnlLayout);
        informacion1PnlLayout.setHorizontalGroup(
            informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion1PnlLayout.createSequentialGroup()
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion1PnlLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroMsjLbl)
                            .addComponent(registroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(informacion1PnlLayout.createSequentialGroup()
                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroLbl)
                                    .addGroup(informacion1PnlLayout.createSequentialGroup()
                                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(segApellidoLbl)
                                            .addComponent(correoELbl)
                                            .addComponent(primerApellidoLbl)
                                            .addComponent(segNombreLbl))
                                        .addGap(10, 10, 10))))
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(primerNombreLbl)))
                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(primerApellidoTFd, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(segNombreTFd, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(validCorreo_Lbl)
                                    .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(validNumLbl)
                                        .addComponent(validNombLbl)
                                        .addComponent(segApellidoTFd)
                                        .addComponent(validApellLbl)
                                        .addComponent(primerNombreTFd)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacion1PnlLayout.createSequentialGroup()
                                            .addComponent(correoTFd, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(numeroTFd)))))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        informacion1PnlLayout.setVerticalGroup(
            informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion1PnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registroMsjLbl)
                .addGap(18, 18, 18)
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroLbl)
                    .addGroup(informacion1PnlLayout.createSequentialGroup()
                        .addComponent(numeroTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacion1PnlLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(primerNombreTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(primerNombreLbl)))
                            .addComponent(validNumLbl))))
                .addGap(7, 7, 7)
                .addComponent(validNombLbl)
                .addGap(18, 18, 18)
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segNombreTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segNombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerApellidoLbl)
                    .addComponent(primerApellidoTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validApellLbl)
                .addGap(20, 20, 20)
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacion1PnlLayout.createSequentialGroup()
                        .addComponent(segApellidoLbl)
                        .addGap(55, 55, 55)
                        .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoELbl)
                            .addComponent(correoTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(segApellidoTFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validCorreo_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(informacion1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        informacionJTP.addTab("tab1", informacion1Pnl);

        puestoCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        puestoCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        puestoCBx.setToolTipText("Seleccioné el puesto que esta asigando el empleado");
        puestoCBx.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 216, 222));
        jLabel5.setText("Este campo es obligatorio");

        puestoLbll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        puestoLbll.setText("Puesto:");

        adscLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adscLbl.setText("Adscripción: ");

        direccionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccionLbl.setText("Direccion");

        plantelCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plantelCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        plantelCBx.setToolTipText("Seleccioné el plantel que esta asigando el empleado");
        plantelCBx.setEnabled(false);

        adscCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adscCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plantel", "Departamento" }));
        adscCBx.setToolTipText("Seleccioné la  adscripción que esta asigando el empleado");
        adscCBx.setEnabled(false);
        adscCBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adscCBxActionPerformed(evt);
            }
        });

        departamentoCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departamentoCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departamentoCBx.setToolTipText("Seleccioné el departamento que esta asigando el empleado");
        departamentoCBx.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(213, 216, 222));
        jLabel6.setText("Este campo es obligatorio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(213, 216, 222));
        jLabel7.setText("Este campo es obligatorio");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(213, 216, 222));
        jLabel9.setText("Este campo es obligatorio");

        plantelLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plantelLbl.setText("Plantel:");

        cancelarBtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelarBtn2.setText("Cancelar");
        cancelarBtn2.setEnabled(false);
        cancelarBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtn2ActionPerformed(evt);
            }
        });

        guardarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardarBtn.setText("Guardar");
        guardarBtn.setEnabled(false);
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        departamentoLbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departamentoLbl1.setText("Departamento:");

        direccionCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccionCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        direccionCBx.setToolTipText("Seleccioné el departamento que esta asigando el empleado");
        direccionCBx.setEnabled(false);

        regresarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regresarBtn.setText("Regresar");
        regresarBtn.setEnabled(false);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(213, 216, 222));
        jLabel10.setText("Este campo es obligatorio");

        javax.swing.GroupLayout informacion2PnlLayout = new javax.swing.GroupLayout(informacion2Pnl);
        informacion2Pnl.setLayout(informacion2PnlLayout);
        informacion2PnlLayout.setHorizontalGroup(
            informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion2PnlLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adscLbl)
                    .addGroup(informacion2PnlLayout.createSequentialGroup()
                        .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plantelLbl)
                            .addComponent(direccionLbl)
                            .addComponent(puestoLbll)
                            .addComponent(departamentoLbl1))
                        .addGap(37, 37, 37)
                        .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(puestoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(adscCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plantelCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(departamentoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(direccionCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(informacion2PnlLayout.createSequentialGroup()
                                .addComponent(cancelarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        informacion2PnlLayout.setVerticalGroup(
            informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacion2PnlLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoLbll)
                    .addComponent(puestoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adscLbl)
                    .addComponent(adscCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantelCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plantelLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(departamentoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionLbl)
                    .addComponent(direccionCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(informacion2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        informacionJTP.addTab("tab2", informacion2Pnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionJTP))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(informacionJTP, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento ejecutado al hacer click en el boton,obteniendo el texto de los
     * campos validando que estos no esten vacios, manda llamar un metodo
     * dependiendo del texto asignado al boton.
     *
     * @param evt Evento al presionar el boton
     */
    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        //Se añaden la informacion de los campos a la lista de objetos
        List<Object> atributos = new ArrayList<>();
        atributos.add(numeroTFd.getText());
        atributos.add(primerNombreTFd.getText());
        atributos.add(segNombreTFd.getText());
        atributos.add(primerApellidoTFd.getText());
        if (segApellidoTFd.getText().isEmpty()) {
            atributos.add("");
        } else {
            atributos.add(segApellidoTFd.getText());
        }
        atributos.add(puestoCBx.getSelectedItem());
        atributos.add(correoTFd.getText() + "@cobachbc.edu.mx");
        atributos.add(adscCBx.getSelectedItem());
        atributos.add(plantelCBx.getSelectedItem());
        atributos.add(departamentoCBx.getSelectedItem());
        atributos.add(direccionCBx.getSelectedItem());
        informacionJTP.setEnabledAt(0, true);
        informacionJTP.setEnabledAt(1, false);
        informacionJTP.setSelectedIndex(0);
        
        //Se limpian los campos
        numeroTFd.setText("");
        primerNombreTFd.setText("");
        segNombreTFd.setText("");
        primerApellidoTFd.setText("");
        segApellidoTFd.setText("");
        correoTFd.setText("");
        puestoCBx.setSelectedIndex(0);
        adscCBx.setSelectedIndex(0);
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        direccionCBx.setSelectedIndex(0);

        //Se selecciona el metodo que se va manadar llamar, obteniendo el texto 
        //contenido en el boton.
        if (!guardarBtn.getText().equalsIgnoreCase("modificar")) {
            control.alta(HelperEntidad.getEmpleado(atributos));
        } else {
            atributos.add(idEmpleadoActual);
            control.modificacion(HelperEntidad.getEmpleado(atributos));
        }
        guardarBtn.setText("Guardar");
        numeroTFd.setBorder(BORDER_ORIGINAL);
        validNumLbl.setForeground(new Color(213, 216, 222));
        primerNombreTFd.setBorder(BORDER_ORIGINAL);
        validNombLbl.setForeground(new Color(213, 216, 222));
        primerApellidoTFd.setBorder(BORDER_ORIGINAL);
        validApellLbl.setForeground(new Color(213, 216, 222));
        correoTFd.setBorder(BORDER_ORIGINAL);
        validCorreo_Lbl.setForeground(new Color(213, 216, 222));
        control.buscarTodos();
        setEnabledPanelInformacion(false);
    }//GEN-LAST:event_guardarBtnActionPerformed


    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        int renglon = tablaTbl.getSelectedRow();
        if (renglon == -1) {
            //Activar el panel
            setEnabledPanelInformacion(true);
        } else {
            //Llenar el panel
            int id = Integer.parseInt((String) model.getValueAt(renglon, 0));
            control.buscar(id);
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    /**
     * Evento ejecutado al hace click en la tabla, se calcula en que columna y
     * renglon se llevo a cabo el click, en caso de ser en la columna eliminar
     * se presentara l a opcion de eliminar el registro correspondiente al
     * renglon.
     *
     * @param evt Evento al hacer click
     */
    private void tablaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTblMouseClicked
        //Obtenelos el renglon y columna donde se hizo click
        int row = tablaTbl.rowAtPoint(evt.getPoint());
        int col = tablaTbl.columnAtPoint(evt.getPoint());
        if (col == 0) {

            int id = Integer.parseInt((String) model.getValueAt(row, 0));
            control.buscar(id);
        } else if (col == 2) {
            //System.out.println("ID: " + model.getValueAt(row, 0));
            //Preguntamos si esta seguro de la eliminacion
            int op = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar este registro?",
                    "Precaucion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (op == 0) {
                //System.out.println("BORRAR");
                //Obtenemos ID de la columna escondida
                int id = Integer.parseInt((String) model.getValueAt(row, 0));
                control.baja(id);
                control.buscarTodos();
            } else {
                model.setValueAt(false, row, 3);
                tablaTbl.clearSelection();
            }
        }
        tablaTbl.clearSelection();
    }//GEN-LAST:event_tablaTblMouseClicked

    /**
     * Evento que se ejecuta cuandore se presiona el boton Buscar, donde se
     * limpian los campos, se obtiene el valor por que se va a agregar.
     *
     * @param evt
     */
    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        //Se limpian los campos
        numeroTFd.setText("");
        primerNombreTFd.setText("");
        segNombreTFd.setText("");
        primerApellidoTFd.setText("");
        segApellidoTFd.setText("");
        correoTFd.setText("");
        numeroTFd.setBorder(BORDER_ORIGINAL);
        primerNombreTFd.setBorder(BORDER_ORIGINAL);
        primerApellidoTFd.setBorder(BORDER_ORIGINAL);
        correoTFd.setBorder(BORDER_ORIGINAL);
        validNumLbl.setForeground(new Color(213, 216, 222));
        validNombLbl.setForeground(new Color(213, 216, 222));
        validApellLbl.setForeground(new Color(213, 216, 222));
        validCorreo_Lbl.setForeground(new Color(213, 216, 222));
        setEnabledPanelInformacion(false);
        if (!nombreBuscarTFd.isEnabled()) {
            nombreBuscarTFd.setEnabled(true);
            adscBuscarCBx.setEnabled(true);
        } else if (!nombreBuscarTFd.getText().isEmpty()) {
            control.buscarPorNombre(nombreBuscarTFd.getText());
        } else if (adscBuscarCBx.getSelectedIndex() == 0) {
            control.buscarTodos();
        } else {
            control.buscarPorAdscripcion((Adscripcion) adscBuscarCBx.getSelectedItem());
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    /**
     * Evento que se ejecuta al presionar el boton Cancelar el cual va a limpiar
     * todos lo campos del panel info y los desahabilitara para realizar otra
     * accion.
     *
     * @param evt
     */
    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        //Se limpian los campos
        numeroTFd.setText("");
        primerNombreTFd.setText("");
        segNombreTFd.setText("");
        primerApellidoTFd.setText("");
        segApellidoTFd.setText("");
        correoTFd.setText("");
        adscCBx.setSelectedIndex(0);
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        guardarBtn.setText("Guardar");
        numeroTFd.setBorder(BORDER_ORIGINAL);
        primerNombreTFd.setBorder(BORDER_ORIGINAL);
        primerApellidoTFd.setBorder(BORDER_ORIGINAL);
        correoTFd.setBorder(BORDER_ORIGINAL);
        validNumLbl.setForeground(new Color(213, 216, 222));
        validNombLbl.setForeground(new Color(213, 216, 222));
        validApellLbl.setForeground(new Color(213, 216, 222));
        validCorreo_Lbl.setForeground(new Color(213, 216, 222));
        setEnabledPanelInformacion(false);

    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * El este evento se produce cuando se intenta teclear en el campo numero,
     * donde solo se permitira el uso de numeros.
     *
     * @param evt
     */
    private void numeroTFdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTFdKeyTyped
        char car = evt.getKeyChar();
        if (numeroTFd.getText().length() >= 10) {
            evt.consume();
        }
        if ((car < '0' || car > '9')
                && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_numeroTFdKeyTyped

    /**
     * Este evento se se produce cuando se intenta teclear en el campo
     * primerNombre, donde solo se permitira el uso de letras y espacios.
     *
     * @param evt
     */
    private void primerNombreTFdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primerNombreTFdKeyTyped
        char car = evt.getKeyChar();
        if (primerNombreTFd.getText().length() >= 20) {
            evt.consume();
        }
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á' //Minúsculas             
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayúsculas             
                && car != 'É'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'ñ'
                && car != 'Ñ') {
            evt.consume();
        }
    }//GEN-LAST:event_primerNombreTFdKeyTyped

    /**
     * Este evento se se produce cuando se intenta teclear en el campo
     * primerApellido, donde solo se permitira el uso de letras y espacios.
     *
     * @param evt
     */
    private void primerApellidoTFdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primerApellidoTFdKeyTyped
        char car = evt.getKeyChar();
        if (primerApellidoTFd.getText().length() >= 20) {
            evt.consume();
        }
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á' //Minúsculas             
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayúsculas             
                && car != 'É'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'ñ'
                && car != 'Ñ'
                && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_primerApellidoTFdKeyTyped

    /**
     * El este evento se produce cuando se intenta teclear en el campo numero,
     * donde solo se permitira el uso de numeros.
     *
     * @param evt
     */
    private void correoTFdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoTFdKeyTyped
        if (correoTFd.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_correoTFdKeyTyped

    private void adscCBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adscCBxActionPerformed
        if (adscCBx.getSelectedIndex() == 0) {
            plantelCBx.setEnabled(false);
            departamentoCBx.setEnabled(false);
            direccionCBx.setEnabled(false);
        } else if (adscCBx.getSelectedIndex() == 1) {
            plantelCBx.setEnabled(false);
            departamentoCBx.setEnabled(true);
            direccionCBx.setEnabled(false);
        } else if (adscCBx.getSelectedIndex() == 2) {
            departamentoCBx.setEnabled(false);
            plantelCBx.setEnabled(true);
            direccionCBx.setEnabled(false);
        } else if (adscCBx.getSelectedIndex() == 3) {
            departamentoCBx.setEnabled(false);
            plantelCBx.setEnabled(false);
            direccionCBx.setEnabled(true);
        }
    }//GEN-LAST:event_adscCBxActionPerformed

    /**
     * Evento que se ejecuta al presionar el boton Cancelar el cual va a limpiar
     * todos lo campos del panel info y los desahabilitara para realizar otra
     * accion.
     *
     * @param evt
     */
    private void cancelarBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtn2ActionPerformed
        //Se limpian los campos
        informacionJTP.setEnabledAt(0, true);
        informacionJTP.setEnabledAt(1, false);
        informacionJTP.setSelectedIndex(0);
        numeroTFd.setText("");
        primerNombreTFd.setText("");
        segNombreTFd.setText("");
        primerApellidoTFd.setText("");
        segApellidoTFd.setText("");
        correoTFd.setText("");
        adscCBx.setSelectedIndex(0);
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        guardarBtn.setText("Guardar");
        numeroTFd.setBorder(BORDER_ORIGINAL);
        primerNombreTFd.setBorder(BORDER_ORIGINAL);
        primerApellidoTFd.setBorder(BORDER_ORIGINAL);
        correoTFd.setBorder(BORDER_ORIGINAL);
        validNumLbl.setForeground(new Color(213, 216, 222));
        validNombLbl.setForeground(new Color(213, 216, 222));
        validApellLbl.setForeground(new Color(213, 216, 222));
        validCorreo_Lbl.setForeground(new Color(213, 216, 222));
        setEnabledPanelInformacion(false);
    }//GEN-LAST:event_cancelarBtn2ActionPerformed

    /**
     * Evento que se ejecuta al presionar el boton Regresar el cual hace la 
     * transicion de un panel a otro
     * @param evt
     */
    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        informacionJTP.setEnabledAt(0, true);
        informacionJTP.setEnabledAt(1, false);
        informacionJTP.setSelectedIndex(0);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        informacionJTP.setEnabledAt(0, false);
        informacionJTP.setEnabledAt(1, true);
        informacionJTP.setSelectedIndex(1);
    }//GEN-LAST:event_siguienteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adscBuscarCBx;
    private javax.swing.JLabel adscBuscarLbl;
    private javax.swing.JComboBox adscCBx;
    private javax.swing.JLabel adscLbl;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton cancelarBtn2;
    private javax.swing.JLabel correoELbl;
    private javax.swing.JTextField correoTFd;
    private javax.swing.JComboBox departamentoCBx;
    private javax.swing.JLabel departamentoLbl1;
    private javax.swing.JComboBox direccionCBx;
    private javax.swing.JLabel direccionLbl;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JPanel informacion1Pnl;
    private javax.swing.JPanel informacion2Pnl;
    private javax.swing.JTabbedPane informacionJTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nombreBuscarLbl;
    private javax.swing.JTextField nombreBuscarTFd;
    private javax.swing.JLabel numeroLbl;
    private javax.swing.JTextField numeroTFd;
    private javax.swing.JLabel opcionLbl;
    private javax.swing.JLabel opcionMsjLbl;
    private javax.swing.JPanel opcionPnl;
    private javax.swing.JComboBox plantelCBx;
    private javax.swing.JLabel plantelLbl;
    private javax.swing.JLabel primerApellidoLbl;
    private javax.swing.JTextField primerApellidoTFd;
    private javax.swing.JLabel primerNombreLbl;
    private javax.swing.JTextField primerNombreTFd;
    private javax.swing.JComboBox puestoCBx;
    private javax.swing.JLabel puestoLbll;
    private javax.swing.JLabel registroLbl;
    private javax.swing.JLabel registroMsjLbl;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel segApellidoLbl;
    private javax.swing.JTextField segApellidoTFd;
    private javax.swing.JLabel segNombreLbl;
    private javax.swing.JTextField segNombreTFd;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JLabel tablaMsjLbl;
    private javax.swing.JScrollPane tablaSPn;
    private javax.swing.JTable tablaTbl;
    private javax.swing.JLabel validApellLbl;
    private javax.swing.JLabel validCorreo_Lbl;
    private javax.swing.JLabel validNombLbl;
    private javax.swing.JLabel validNumLbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setMensaje(String mensaje) {
        switch (mensaje) {
            case "El numero de empleado ya existe":
                numeroTFd.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(255, 106, 106)),
                        BORDER_ORIGINAL));
                validNumLbl.setText("El numero del empleado ya existe");
                validNumLbl.setForeground(new Color(240, 0, 0));
                break;
            case "Se ha guardado existosamente":
                JOptionPane.showMessageDialog(this, mensaje,
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Se ha modificado existosamente":
                JOptionPane.showMessageDialog(this, mensaje,
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, mensaje,
                        "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Metodo que recibe una matriz, donde se obtendran sus valores para
     * añadirlos a la modelo de la tabla, también se ocultara la columna id y se
     * le dara se redefinira el ancho de la columna 0.
     *
     * @param info Matriz String para vaciar en tabla
     */
    @Override
    public void setTabla(String[][] info) {
        model.setDataVector(info, titulosTabla);
        TableColumn tc = tablaTbl.getColumnModel().getColumn(3);
        tc.setCellEditor(tablaTbl.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(tablaTbl.getDefaultRenderer(Boolean.class));
        //Esconder columna ID
        tc = tablaTbl.getColumnModel().getColumn(0);
        tablaTbl.getColumnModel().removeColumn(tc);
        tablaTbl.getColumnModel().getColumn(1).setPreferredWidth(230);
    }

    @Override
    public void setLista(List info, int i) {
        if (info.isEmpty()) {
            return;
        }
        switch (i) {
            case 1:
                puestoModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    puestoModel.addElement(info.get(j));
                }
                puestoModel.insertElementAt(new Puesto(), 0);
                Puesto obj =(Puesto)puestoModel.getElementAt(1);
                puestoCBx.setSelectedIndex(0);
                break;
            case 2:
                plantelModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    plantelModel.addElement(info.get(j));
                }
                plantelModel.insertElementAt(new Plantel(), 0);
                plantelCBx.setSelectedIndex(0);
                break;
            case 3:
                dptoModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    dptoModel.addElement(info.get(j));
                }
                dptoModel.insertElementAt(new Departamento(), 0);
                departamentoCBx.setSelectedIndex(0);
                break;
            case 4:
                adscripModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    adscripModel.addElement(info.get(j));
                }
                adscripModel.insertElementAt(new Departamento(), 0);
                adscCBx.setSelectedIndex(0);
                break;
            case 5:
                dirModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    dirModel.addElement(info.get(j));
                }
                dirModel.insertElementAt(new Departamento(), 0);
                direccionCBx.setSelectedIndex(0);
                break;
        }
    }

    public void llenarTodo() {
        control.buscarTodos();
        control.setClass(Puesto.class);
        control.buscarTodosLista(1);
        control.setClass(Plantel.class);
        control.buscarTodosLista(2);
        control.setClass(Departamento.class);
        control.buscarTodosLista(3);
        control.setClass(Adscripcion.class);
        control.buscarTodosLista(4);
        control.setClass(Direccion.class);
        control.buscarTodosLista(5);
        control.setClass(Empleado.class);
        setEnabledPanelInformacion(false);

    }

    // Metodo que hace visibles o invisibles los campos del panel informacion
    private void setEnabledPanelInformacion(boolean b) {
        numeroTFd.setEnabled(b);
        primerNombreTFd.setEnabled(b);
        segNombreTFd.setEnabled(b);
        primerApellidoTFd.setEnabled(b);
        segApellidoTFd.setEnabled(b);
        correoTFd.setEnabled(b);
        puestoCBx.setEnabled(b);
        adscCBx.setEnabled(b);
        direccionCBx.setEnabled(b);
        guardarBtn.setEnabled(b);
        cancelarBtn.setEnabled(b);
        cancelarBtn2.setEnabled(b);
        regresarBtn.setEnabled(b);
        siguienteBtn.setEnabled(b);
    }

    /**
     * Metodo sobrescrito de la clase comunicador que recibe una Lista con la
     * los resultados de una busqueda especifica y vaciarlo en los campos y
     * checkbox
     *
     * @param info Lista de Objeto con información de búsqueda.
     */
    @Override
    public void setInfo(List info) {
        setEnabledPanelInformacion(true);
        idEmpleadoActual = (int) info.get(0);
        numeroTFd.setText((String) info.get(1));
        primerNombreTFd.setText((String) info.get(2));
        segNombreTFd.setText((String) info.get(3));
        primerApellidoTFd.setText((String) info.get(4));
        segApellidoTFd.setText((String) info.get(5));
        puestoModel.setSelectedItem(info.get(6));
        String[] correo = ((String) info.get(7)).split("@");
        correoTFd.setText(correo[0]);
        plantelModel.setSelectedItem(info.get(8));
        adscripModel.setSelectedItem(info.get(9));
        dptoModel.setSelectedItem(info.get(10));
        dirModel.setSelectedItem(info.get(11));
        adscCBx.setEnabled(true);
        puestoCBx.setEnabled(true);
        guardarBtn.setText("Modificar");
    }

    @Override
    public void focusGained(FocusEvent e) {
        Object fuente = e.getSource();
        if (fuente == numeroTFd) {
            numeroTFd.setBorder(BORDER_ORIGINAL);
            validNumLbl.setForeground(new Color(213, 216, 222));
        } else if (fuente == primerNombreTFd) {
            primerNombreTFd.setBorder(BORDER_ORIGINAL);
            validNombLbl.setForeground(new Color(213, 216, 222));
        } else if (fuente == primerApellidoTFd) {
            primerApellidoTFd.setBorder(BORDER_ORIGINAL);
            validApellLbl.setForeground(new Color(213, 216, 222));
        } else if (fuente == correoTFd) {
            correoTFd.setBorder(BORDER_ORIGINAL);
            validCorreo_Lbl.setForeground(new Color(213, 216, 222));
        }
    }

    @Override
    public void focusLost(FocusEvent e) {
        Object fuente = e.getSource();
        if (fuente == numeroTFd) {
            if (numeroTFd.getText().isEmpty()) {
                numeroTFd.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(255, 106, 106)),
                        BORDER_ORIGINAL));
                validNumLbl.setText("Este campo es obligatorio");
                validNumLbl.setForeground(new Color(240, 0, 0));
            } else {
                control.validarPorNumero(Integer.parseInt(numeroTFd.getText()));
//                numeroTFd.setBorder(BORDER_ORIGINAL);
//                validNumLbl.setForeground(new Color(213, 216, 222));

            }
        } else if (fuente == primerNombreTFd) {
            if (primerNombreTFd.getText().isEmpty()) {
                primerNombreTFd.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(255, 106, 106)),
                        BORDER_ORIGINAL));
                validNombLbl.setText("Este campo es obligatorio");
                validNombLbl.setForeground(new Color(240, 0, 0));
            }
        } else if (fuente == primerApellidoTFd) {
            if (primerApellidoTFd.getText().isEmpty()) {
                primerApellidoTFd.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(255, 106, 106)),
                        BORDER_ORIGINAL));
                validApellLbl.setText("Este campo es obligatorio");
                validApellLbl.setForeground(new Color(240, 0, 0));
            }
        } else if (fuente == correoTFd) {
            if (correoTFd.getText().isEmpty()) {
                correoTFd.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(255, 106, 106)),
                        BORDER_ORIGINAL));
                validCorreo_Lbl.setText("Este campo es obligatorio");
                validCorreo_Lbl.setForeground(new Color(240, 0, 0));
            }
        }
    }

    public void llenarDatos(Object evento) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
