/*}
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.cobach.vista;

import java.awt.print.PrinterException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.edu.cobach.persistencia.entidades.Departamento;
import mx.edu.cobach.persistencia.entidades.Direccion;
import mx.edu.cobach.persistencia.entidades.ImplementacionEvento;
import mx.edu.cobach.persistencia.entidades.Plantel;
import mx.edu.cobach.vista.controlador.ReporteControlador;

/**
 *
 * @author Fernando
 */
public class PnlReporteEvento extends javax.swing.JPanel implements Comunicador {

    
    ReporteControlador control;
    private final DefaultComboBoxModel departamentoModel, dirModel;
    private final DefaultComboBoxModel plantelModel;
    private final DefaultTableModel model;
    private final String[] titulosTabla;
    
    /**
     * Constructor del PnlRegistrarEvento e instancia la clase EventoControlador. 
     * Se crea modelo de la tabla y se realiza la busqueda 
     */
    public PnlReporteEvento() {
        initComponents();
        this.titulosTabla = new String[]{"Fecha inicial", "Fecha final", "Nombre", "Sede", "Proveedor"};
        model = new DefaultTableModel(titulosTabla, 6) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        eventoTbl.setModel(model);
        control = new ReporteControlador(this, ImplementacionEvento.class);
        departamentoModel = new DefaultComboBoxModel();
        plantelModel = new DefaultComboBoxModel();
        dirModel = new DefaultComboBoxModel();
        departamentoCBx.setModel(departamentoModel);
        direccionCBx.setModel(dirModel);
        plantelCBx.setModel(plantelModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaIDCh1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        reporteCursoTb = new javax.swing.JTabbedPane();
        departamentoPnl = new javax.swing.JPanel();
        departamentoLbl = new javax.swing.JLabel();
        departamentoCBx = new javax.swing.JComboBox();
        opcionDeptoLbl = new javax.swing.JLabel();
        opcionDeptoMsjLbl = new javax.swing.JLabel();
        buscarDepartamentoBtnl = new javax.swing.JButton();
        direccionPnl = new javax.swing.JPanel();
        direccionLbl = new javax.swing.JLabel();
        direccionCBx = new javax.swing.JComboBox();
        opcionDirLbl = new javax.swing.JLabel();
        opcionDirMsjLbl = new javax.swing.JLabel();
        buscarDirBtn = new javax.swing.JButton();
        plantelPnl = new javax.swing.JPanel();
        plantelLbl = new javax.swing.JLabel();
        plantelCBx = new javax.swing.JComboBox();
        opcionPlantelMsjLbl = new javax.swing.JLabel();
        opcionLbl = new javax.swing.JLabel();
        buscarPlantelBtn = new javax.swing.JButton();
        fechaPnl = new javax.swing.JPanel();
        fechaInicioLbl = new javax.swing.JLabel();
        fechaHastaLbl = new javax.swing.JLabel();
        buscarFechaBtn = new javax.swing.JButton();
        opcionFechaMsjLbl = new javax.swing.JLabel();
        opcionFechaLbl = new javax.swing.JLabel();
        fechaHastaDCh = new com.toedter.calendar.JDateChooser();
        fechaLbl = new javax.swing.JLabel();
        fechaInicioDCh = new com.toedter.calendar.JDateChooser();
        informacionPnl = new javax.swing.JPanel();
        eventoSPn = new javax.swing.JScrollPane();
        eventoTbl = new javax.swing.JTable();
        imprimirBtn = new javax.swing.JButton();
        infoLbl = new javax.swing.JLabel();

        fechaIDCh1.setDateFormatString("dd/MM/yyyy");
        fechaIDCh1.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        reporteCursoTb.setMaximumSize(new java.awt.Dimension(408, 587));
        reporteCursoTb.setMinimumSize(new java.awt.Dimension(408, 587));
        reporteCursoTb.setPreferredSize(new java.awt.Dimension(408, 587));

        departamentoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departamentoLbl.setText("Departamento: ");

        departamentoCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        opcionDeptoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcionDeptoLbl.setText("Opciones ");

        opcionDeptoMsjLbl.setText("Seleccione el departamento y presione el botón Buscar ");

        buscarDepartamentoBtnl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarDepartamentoBtnl.setText("Buscar");
        buscarDepartamentoBtnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDepartamentoBtnlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout departamentoPnlLayout = new javax.swing.GroupLayout(departamentoPnl);
        departamentoPnl.setLayout(departamentoPnlLayout);
        departamentoPnlLayout.setHorizontalGroup(
            departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departamentoPnlLayout.createSequentialGroup()
                .addGroup(departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, departamentoPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarDepartamentoBtnl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(departamentoPnlLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(departamentoPnlLayout.createSequentialGroup()
                                .addComponent(departamentoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(departamentoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(departamentoPnlLayout.createSequentialGroup()
                                .addGroup(departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionDeptoMsjLbl)
                                    .addComponent(opcionDeptoLbl))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        departamentoPnlLayout.setVerticalGroup(
            departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departamentoPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionDeptoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionDeptoMsjLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(departamentoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(buscarDepartamentoBtnl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        reporteCursoTb.addTab("Por departamento", departamentoPnl);

        direccionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccionLbl.setText("Dirección");

        direccionCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        opcionDirLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcionDirLbl.setText("Opciones ");

        opcionDirMsjLbl.setText("Seleccione el dirección y presione el botón Buscar ");

        buscarDirBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarDirBtn.setText("Buscar");
        buscarDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout direccionPnlLayout = new javax.swing.GroupLayout(direccionPnl);
        direccionPnl.setLayout(direccionPnlLayout);
        direccionPnlLayout.setHorizontalGroup(
            direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(direccionPnlLayout.createSequentialGroup()
                .addGroup(direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, direccionPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(direccionPnlLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(direccionPnlLayout.createSequentialGroup()
                                .addGroup(direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionDirMsjLbl)
                                    .addComponent(opcionDirLbl))
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addGroup(direccionPnlLayout.createSequentialGroup()
                                .addComponent(direccionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(direccionCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        direccionPnlLayout.setVerticalGroup(
            direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(direccionPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionDirLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionDirMsjLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(direccionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLbl)
                    .addComponent(direccionCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(buscarDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        reporteCursoTb.addTab("Por dirección", direccionPnl);

        plantelLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plantelLbl.setText("Plantel:");

        plantelCBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plantelCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        opcionPlantelMsjLbl.setText("Seleccion el plante y presione el botón buscar");

        opcionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcionLbl.setText("Opciones ");

        buscarPlantelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarPlantelBtn.setText("Buscar");
        buscarPlantelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPlantelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plantelPnlLayout = new javax.swing.GroupLayout(plantelPnl);
        plantelPnl.setLayout(plantelPnlLayout);
        plantelPnlLayout.setHorizontalGroup(
            plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantelPnlLayout.createSequentialGroup()
                .addGroup(plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plantelPnlLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plantelPnlLayout.createSequentialGroup()
                                .addGroup(plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionPlantelMsjLbl)
                                    .addComponent(opcionLbl))
                                .addGap(0, 151, Short.MAX_VALUE))
                            .addGroup(plantelPnlLayout.createSequentialGroup()
                                .addComponent(plantelLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plantelCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plantelPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarPlantelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        plantelPnlLayout.setVerticalGroup(
            plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantelPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionPlantelMsjLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plantelPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantelLbl)
                    .addComponent(plantelCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(buscarPlantelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        reporteCursoTb.addTab("Por plantel", plantelPnl);

        fechaInicioLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaInicioLbl.setText("Fecha de:");

        fechaHastaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaHastaLbl.setText("Hasta:");

        buscarFechaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarFechaBtn.setText("Buscar");
        buscarFechaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFechaBtnActionPerformed(evt);
            }
        });

        opcionFechaMsjLbl.setText("Seleccione el rango de fechas y presione el botón buscar ");

        opcionFechaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcionFechaLbl.setText("Opciones ");

        fechaHastaDCh.setDateFormatString("dd/MM/yyyy");
        fechaHastaDCh.setFocusable(false);
        fechaHastaDCh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaHastaDChPropertyChange(evt);
            }
        });

        fechaLbl.setText("<HTML>Si deseas ingresar la fecha con el teclado sigue el formato<BR> D/M/A. Ejem. 01/12/2015 </HTML>");

        fechaInicioDCh.setDateFormatString("dd/MM/yyyy");
        fechaInicioDCh.setFocusable(false);
        fechaInicioDCh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaInicioDChPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout fechaPnlLayout = new javax.swing.GroupLayout(fechaPnl);
        fechaPnl.setLayout(fechaPnlLayout);
        fechaPnlLayout.setHorizontalGroup(
            fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaPnlLayout.createSequentialGroup()
                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fechaPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarFechaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fechaPnlLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fechaPnlLayout.createSequentialGroup()
                                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionFechaMsjLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opcionFechaLbl)
                                    .addComponent(fechaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(fechaPnlLayout.createSequentialGroup()
                                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fechaHastaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaInicioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaInicioDCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaHastaDCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        fechaPnlLayout.setVerticalGroup(
            fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionFechaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionFechaMsjLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicioLbl)
                    .addComponent(fechaInicioDCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fechaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaHastaLbl)
                    .addComponent(fechaHastaDCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(buscarFechaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        reporteCursoTb.addTab("Por fechas", fechaPnl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reporteCursoTb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reporteCursoTb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        informacionPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        informacionPnl.setMaximumSize(new java.awt.Dimension(768, 564));
        informacionPnl.setMinimumSize(new java.awt.Dimension(768, 564));

        eventoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha inicial", "Fecha final", "Nombre", "Sede", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventoSPn.setViewportView(eventoTbl);
        if (eventoTbl.getColumnModel().getColumnCount() > 0) {
            eventoTbl.getColumnModel().getColumn(0).setResizable(false);
            eventoTbl.getColumnModel().getColumn(1).setResizable(false);
            eventoTbl.getColumnModel().getColumn(2).setResizable(false);
            eventoTbl.getColumnModel().getColumn(3).setResizable(false);
            eventoTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        imprimirBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imprimirBtn.setText("Imprimir");
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });

        infoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infoLbl.setText("Información del los eventos realizados");

        javax.swing.GroupLayout informacionPnlLayout = new javax.swing.GroupLayout(informacionPnl);
        informacionPnl.setLayout(informacionPnlLayout);
        informacionPnlLayout.setHorizontalGroup(
            informacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventoSPn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacionPnlLayout.createSequentialGroup()
                        .addGap(0, 636, Short.MAX_VALUE)
                        .addComponent(imprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacionPnlLayout.createSequentialGroup()
                        .addComponent(infoLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        informacionPnlLayout.setVerticalGroup(
            informacionPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(infoLbl)
                .addGap(18, 18, 18)
                .addComponent(eventoSPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informacionPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento ejecutado al presionar el botón, imprime en pdf la tabla que contiene
     * la informacion de eventos
     */
    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed
        try {
            eventoTbl.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PnlReporteEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimirBtnActionPerformed

    /**
     * Metodo que se ejecuta al cambiar la fecha del componente aFechaDCh. Se ajusta
     * la fecha maxima del componente deFechaDCh y se ajusta si esta ya es mayor que
     * la actual.
     * @param evt Evento de cambio de propiedad
     */
    private void fechaHastaDChPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaHastaDChPropertyChange
        Date hastaFecha = fechaHastaDCh.getDate();
        if(hastaFecha != null){
            fechaInicioDCh.setMaxSelectableDate(hastaFecha);
            if(fechaInicioDCh.getDate() != null && fechaInicioDCh.getDate().after(hastaFecha))
            fechaInicioDCh.setDate(hastaFecha);
        }
    }//GEN-LAST:event_fechaHastaDChPropertyChange

    /**
     * Metodo que se ejecuta al presionar el botón. obteniendo la fecha inicial y
     * final.
     * @param evt Evento de cambio de propiedad
     */
    private void buscarFechaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFechaBtnActionPerformed
        control.generarEventosPorFecha(fechaInicioDCh.getDate(), fechaHastaDCh.getDate());
        fechaInicioDCh.setDate(null);
        fechaHastaDCh.setDate(null);
    }//GEN-LAST:event_buscarFechaBtnActionPerformed

    /**
     * Metodo que se ejecuta al presionar el botón. obteniendo la fecha inicial y
     * final.
     * @param evt Evento de cambio de propiedad
     */
    private void buscarPlantelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPlantelBtnActionPerformed
        control.generarReportePorPlantel((Plantel) plantelCBx.getSelectedItem());
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        direccionCBx.setSelectedIndex(0);
        fechaInicioDCh.setDate(null);
        fechaHastaDCh.setDate(null);
    }//GEN-LAST:event_buscarPlantelBtnActionPerformed

    /**
     * Metodo que se ejecuta al presionar el botón. obteniendo el departamento.
     * @param evt Evento que obtiene el deparamento
     */
    private void buscarDepartamentoBtnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDepartamentoBtnlActionPerformed
        control.generarReportePorDepartamento((Departamento) departamentoCBx.getSelectedItem());
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        direccionCBx.setSelectedIndex(0);
        fechaInicioDCh.setDate(null);
        fechaHastaDCh.setDate(null);
    }//GEN-LAST:event_buscarDepartamentoBtnlActionPerformed

    /**
     * Metodo que se ejecuta al presionar el botón. obteniendo el direccion.
     * @param evt Evento que obtiene el deparamento
     */
    private void buscarDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDirBtnActionPerformed
        control.generarReportePorDireccion((Direccion) direccionCBx.getSelectedItem());
        plantelCBx.setSelectedIndex(0);
        departamentoCBx.setSelectedIndex(0);
        direccionCBx.setSelectedIndex(0);
        fechaInicioDCh.setDate(null);
        fechaHastaDCh.setDate(null);
    }//GEN-LAST:event_buscarDirBtnActionPerformed

    /**
     * Metodo que se ejecuta al cambiar la fecha del componente deFechaDCh. Se ajusta
     * la fecha minima del componente aFechaDCh y se ajusta si esta ya es menor que
     * la actual.
     * @param evt Evento de cambio de propiedad
     */
    private void fechaInicioDChPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaInicioDChPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicioDChPropertyChange
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDepartamentoBtnl;
    private javax.swing.JButton buscarDirBtn;
    private javax.swing.JButton buscarFechaBtn;
    private javax.swing.JButton buscarPlantelBtn;
    private javax.swing.JComboBox departamentoCBx;
    private javax.swing.JLabel departamentoLbl;
    private javax.swing.JPanel departamentoPnl;
    private javax.swing.JComboBox direccionCBx;
    private javax.swing.JLabel direccionLbl;
    private javax.swing.JPanel direccionPnl;
    private javax.swing.JScrollPane eventoSPn;
    private javax.swing.JTable eventoTbl;
    private com.toedter.calendar.JDateChooser fechaHastaDCh;
    private javax.swing.JLabel fechaHastaLbl;
    private com.toedter.calendar.JDateChooser fechaIDCh1;
    private com.toedter.calendar.JDateChooser fechaInicioDCh;
    private javax.swing.JLabel fechaInicioLbl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JPanel fechaPnl;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JPanel informacionPnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel opcionDeptoLbl;
    private javax.swing.JLabel opcionDeptoMsjLbl;
    private javax.swing.JLabel opcionDirLbl;
    private javax.swing.JLabel opcionDirMsjLbl;
    private javax.swing.JLabel opcionFechaLbl;
    private javax.swing.JLabel opcionFechaMsjLbl;
    private javax.swing.JLabel opcionLbl;
    private javax.swing.JLabel opcionPlantelMsjLbl;
    private javax.swing.JComboBox plantelCBx;
    private javax.swing.JLabel plantelLbl;
    private javax.swing.JPanel plantelPnl;
    private javax.swing.JTabbedPane reporteCursoTb;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo se manda hacer consultas de tablas y e insertar los valores en los
     * modelos de los ComboBox
     */
    public void llenarTodo() {
        control.setClass(Departamento.class);
        control.buscarTodosLista(1);
        control.setClass(Plantel.class);
        control.buscarTodosLista(2);
        control.setClass(Direccion.class);
        control.buscarTodosLista(3);
    }
    
    /**
     * Metodo sobrescrito de la clase comunicador que recibe un objeto con la
     * los resultados de una busqueda especifica, que no tiene ninguna
     * funcionalidad en este componente.
     */
    @Override
    public void setMensaje(String mensaje) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Metodo que recibe una matriz, donde se obtendran sus valores para
     * añadirlos a la modelo de la tabla, también se ocultara la columna id y se
     * le dara se redefinira el ancho de la columna 0.
     *
     * @param info Matriz String para vaciar en tabla
     */
    @Override
    public void setTabla(String[][] info) {
        if (info.length==0) {
            JOptionPane.showMessageDialog(null, "No se Encontro la busqueda");
        } else {
        model.setDataVector(info, titulosTabla);
        eventoTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
        eventoTbl.getColumnModel().getColumn(1).setPreferredWidth(10);
        }
    }

    /**
     * Metodo sobrescrito de la clase comunicador que recibe un objeto con la
     * los resultados de una busqueda especifica, que no tiene ninguna
     * funcionalidad en este componente.
     *
     * @param evento Objecto de la entidad de tipo evento
     */
    @Override
    public void setInfo(List info) {

    }

    /**
     * Metodo sobrescrito de la clase comunicador que recibe una Lista con la
     * los resultados de una busqueda especifica y vaciarlo en los campos y
     * checkbox
     *
     * @param info Lista de Objeto con información de búsqueda.
     */
    @Override
    public void setLista(List info, int i) {
        if (info.isEmpty()) {
            return;
        }
        switch (i) {
            case 1:
                departamentoModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    departamentoModel.addElement(info.get(j));
                }

                departamentoModel.insertElementAt(new Departamento(), 0);
                departamentoCBx.setSelectedIndex(0);
                break;
            case 2: 
                plantelModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    plantelModel.addElement(info.get(j));
                }

                plantelModel.insertElementAt(new Departamento(), 0);
                plantelCBx.setSelectedIndex(0);
                break;
            case 3:
                dirModel.removeAllElements();
                for (int j = 0; j < info.size(); j++) {
                    dirModel.addElement(info.get(j));
                }

                dirModel.insertElementAt(new Departamento(), 0);
                direccionCBx.setSelectedIndex(0);
                break;
        }
    }

    /**
     * Metodo sobrescrito de la clase comunicador que recibe un objeto con la
     * los resultados de una busqueda especifica, que no tiene ninguna
     * funcionalidad en este componente.
     *
     * @param evento Objecto de la entidad de tipo evento
     */
    @Override
    public void llenarDatos(Object evento) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
