/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.cobach.vista;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import mx.edu.cobach.persistencia.entidades.Curso;
import mx.edu.cobach.vista.controlador.EncuestaControlador;

/**
 *
 * @author liuts
 */
public class PnlSeguimiento extends javax.swing.JPanel implements Comunicador{

    private final EncuestaControlador control;
    private final DefaultTableModel cursosTblModel;
    private final DefaultComboBoxModel cursosCBxModel;
    private final String[] titulosTabla = {"ID", "FechaInicial", "Nombre del curso",
        "Estado", "Eliminar"};
    private PnlEncuestaResultado resultadoPnl;
    private PnlAgregarAspectos agregarAspectosPnl;
    private PnlAgregarEmpleados agregarEmpleadosPnl;
    
    public PnlSeguimiento() {
        initComponents();
        agregar();
        control = new EncuestaControlador(this);
        cursosTblModel = new DefaultTableModel(titulosTabla, 10);
        cursosTbl.setModel(cursosTblModel);
        
        cursosCBxModel = new DefaultComboBoxModel();
        cursoCBx.setModel(cursosCBxModel);
        
        TableColumn tc = cursosTbl.getColumnModel().getColumn(0);
        cursosTbl.getColumnModel().removeColumn(tc);
    }

    /*
    En este metodos agregamos y configuramos lo paneles de Realizar Encuesta y
    de Resultados. Este metodo se ejecuta al llamar el constructor.
    */
    private void agregar(){
        resultadoPnl = new PnlEncuestaResultado();
        
        resultadoPnl.setLocation(408,0);
        resultadoPnl.setSize(773,589);
        resultadoPnl.setVisible(false);
        add(resultadoPnl);
        
        agregarAspectosPnl = new PnlAgregarAspectos();
        agregarAspectosPnl.setLocation(408,0);
        agregarAspectosPnl.setSize(773,589);
        agregarAspectosPnl.setVisible(true);
        add(agregarAspectosPnl);
        
        agregarEmpleadosPnl = new PnlAgregarEmpleados();
        agregarEmpleadosPnl.setLocation(408,0);
        agregarEmpleadosPnl.setSize(773,589);
        agregarEmpleadosPnl.setVisible(false);
        add(agregarEmpleadosPnl);
        
        agregarAspectosPnl.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentShown(ComponentEvent e){                
            }
            
            @Override
            public void componentHidden(ComponentEvent e){
                agregarEmpleadosPnl.setVisible(true);
            }
        });
        
        agregarEmpleadosPnl.addComponentListener(new ComponentAdapter(){
            @Override
            public void componentShown(ComponentEvent e){                
            }
            
            @Override
            public void componentHidden(ComponentEvent e){
                agregarAspectosPnl.setVisible(true);
            }
        });
    }
    
    /*
    Este metodo es utilizado para llenar las listas con la informacion de la 
    base de datos. Se ejecuta antes de entrar al panel para que una vez que se
    entre se mostrara todos los datos correspondientes.
    */
    public void llenarTodo(){
        control.setClass(Curso.class);
        control.buscarTodosLista(1);
        agregarAspectosPnl.llenarTodo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionSeguimiento_Tb = new javax.swing.JTabbedPane();
        realizarEncuesta_Pnl = new javax.swing.JPanel();
        disenarEncuestaTltLbl = new javax.swing.JLabel();
        disenarEncuestaInsLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cursoCBx = new javax.swing.JComboBox();
        deFechaDCh = new com.toedter.calendar.JDateChooser();
        deFechaLbl = new javax.swing.JLabel();
        aFechaDCh = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        cursosTbl = new javax.swing.JTable();
        resultado_Pnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titulo_RE_Lbl1 = new javax.swing.JLabel();
        seleccion_BC_CBx = new javax.swing.JComboBox();
        nombre_BC_Lbl = new javax.swing.JLabel();
        sede_BC_Lbl = new javax.swing.JLabel();
        sede_BC_TFd = new javax.swing.JTextField();
        buscar_BC_Btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCursos_BC_Tbl = new javax.swing.JTable();

        opcionSeguimiento_Tb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        realizarEncuesta_Pnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                realizarEncuesta_PnlComponentShown(evt);
            }
        });

        disenarEncuestaTltLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        disenarEncuestaTltLbl.setText("<html>Selecci&oacute;n de curso</html>");

        disenarEncuestaInsLbl.setText("<html>Seleccionar el curso asociado con la encuesta a realizar y<br> la fecha en la que este se llevar&aacute; a cabo.</html>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setLabelFor(cursoCBx);
        jLabel1.setText("Curso:");

        cursoCBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deFechaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deFechaLbl.setText("De:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("A:");

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        cursosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha Inicial", "Nombre del curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursosTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(cursosTbl);
        if (cursosTbl.getColumnModel().getColumnCount() > 0) {
            cursosTbl.getColumnModel().getColumn(0).setResizable(false);
            cursosTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout realizarEncuesta_PnlLayout = new javax.swing.GroupLayout(realizarEncuesta_Pnl);
        realizarEncuesta_Pnl.setLayout(realizarEncuesta_PnlLayout);
        realizarEncuesta_PnlLayout.setHorizontalGroup(
            realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(realizarEncuesta_PnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarBtn)
                    .addGroup(realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(realizarEncuesta_PnlLayout.createSequentialGroup()
                            .addComponent(deFechaLbl)
                            .addGap(18, 18, 18)
                            .addComponent(deFechaDCh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aFechaDCh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(disenarEncuestaInsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(disenarEncuestaTltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(realizarEncuesta_PnlLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(cursoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        realizarEncuesta_PnlLayout.setVerticalGroup(
            realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarEncuesta_PnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(disenarEncuestaTltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(disenarEncuestaInsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cursoCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(deFechaDCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aFechaDCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deFechaLbl))
                .addGap(18, 18, 18)
                .addComponent(buscarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        opcionSeguimiento_Tb.addTab("<html>Dise&ntilde;ar encuesta</html>", realizarEncuesta_Pnl);

        resultado_Pnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                resultado_PnlComponentShown(evt);
            }
        });

        jLabel2.setText("<html>Buscar el curso a traves del nombre y sede, posteriormente <br>seleccionar el curso para mostrar los resultados de encuestas <html>");

        titulo_RE_Lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo_RE_Lbl1.setText("Opciones");

        seleccion_BC_CBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seleccion_BC_CBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccion_BC_CBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion_BC_CBxActionPerformed(evt);
            }
        });

        nombre_BC_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre_BC_Lbl.setText("Nombre del curso: ");

        sede_BC_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sede_BC_Lbl.setText("Sede del curso:");

        sede_BC_TFd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buscar_BC_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar_BC_Btn.setText("Buscar");

        tablaCursos_BC_Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha Inicial", "Nombre del curso", "Sede", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaCursos_BC_Tbl);
        if (tablaCursos_BC_Tbl.getColumnModel().getColumnCount() > 0) {
            tablaCursos_BC_Tbl.getColumnModel().getColumn(0).setResizable(false);
            tablaCursos_BC_Tbl.getColumnModel().getColumn(1).setResizable(false);
            tablaCursos_BC_Tbl.getColumnModel().getColumn(2).setResizable(false);
            tablaCursos_BC_Tbl.getColumnModel().getColumn(2).setHeaderValue("Sede");
            tablaCursos_BC_Tbl.getColumnModel().getColumn(3).setResizable(false);
            tablaCursos_BC_Tbl.getColumnModel().getColumn(3).setHeaderValue("Estado");
        }

        javax.swing.GroupLayout resultado_PnlLayout = new javax.swing.GroupLayout(resultado_Pnl);
        resultado_Pnl.setLayout(resultado_PnlLayout);
        resultado_PnlLayout.setHorizontalGroup(
            resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultado_PnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_RE_Lbl1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultado_PnlLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscar_BC_Btn)
                    .addGroup(resultado_PnlLayout.createSequentialGroup()
                        .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sede_BC_Lbl)
                            .addComponent(nombre_BC_Lbl))
                        .addGap(18, 18, 18)
                        .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seleccion_BC_CBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sede_BC_TFd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        resultado_PnlLayout.setVerticalGroup(
            resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultado_PnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo_RE_Lbl1)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_BC_Lbl)
                    .addComponent(seleccion_BC_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sede_BC_Lbl)
                    .addComponent(sede_BC_TFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar_BC_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        opcionSeguimiento_Tb.addTab("Resultados", resultado_Pnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionSeguimiento_Tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 773, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionSeguimiento_Tb)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void realizarEncuesta_PnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_realizarEncuesta_PnlComponentShown
        resultadoPnl.setVisible(false);
        agregarAspectosPnl.setVisible(true);
    }//GEN-LAST:event_realizarEncuesta_PnlComponentShown

    private void resultado_PnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_resultado_PnlComponentShown
        resultadoPnl.setVisible(true);
        agregarAspectosPnl.setVisible(false);
    }//GEN-LAST:event_resultado_PnlComponentShown

    private void seleccion_BC_CBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion_BC_CBxActionPerformed
        
    }//GEN-LAST:event_seleccion_BC_CBxActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        Object curso = cursoCBx.getSelectedItem();
        Date de = deFechaDCh.getDate();
        Date hasta = aFechaDCh.getDate();
        if(cursoCBx.getSelectedIndex() != 0){
            control.buscarImplementacion(curso);
        }else{
            control.buscarImplementacion(de, hasta);
        }
        
    }//GEN-LAST:event_buscarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser aFechaDCh;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton buscar_BC_Btn;
    private javax.swing.JComboBox cursoCBx;
    private javax.swing.JTable cursosTbl;
    private com.toedter.calendar.JDateChooser deFechaDCh;
    private javax.swing.JLabel deFechaLbl;
    private javax.swing.JLabel disenarEncuestaInsLbl;
    private javax.swing.JLabel disenarEncuestaTltLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nombre_BC_Lbl;
    private javax.swing.JTabbedPane opcionSeguimiento_Tb;
    private javax.swing.JPanel realizarEncuesta_Pnl;
    private javax.swing.JPanel resultado_Pnl;
    private javax.swing.JLabel sede_BC_Lbl;
    private javax.swing.JTextField sede_BC_TFd;
    private javax.swing.JComboBox seleccion_BC_CBx;
    private javax.swing.JTable tablaCursos_BC_Tbl;
    private javax.swing.JLabel titulo_RE_Lbl1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void setTabla(String[][] info) {
        cursosTblModel.setDataVector(info, titulosTabla);
    }

    @Override
    public void setInfo(List info) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setLista(List info, int i) {
        cursosCBxModel.removeAllElements();
        for(int j = 0; j < info.size(); j++){
            cursosCBxModel.addElement(info.get(j));
        }
        cursosCBxModel.insertElementAt(new Curso(), 0);
        cursoCBx.setSelectedIndex(0);
    }
}
