/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.cobach.vista;

import java.awt.event.ItemEvent;

/**
 *
 * @author liuts
 */
public class PnlSeguimiento extends javax.swing.JPanel {

    /**
     * Creates new form PnlSeguimiento
     */
    
    private PnlEncuestaResultado resultadoPnl;
    private PnlRealizarEncuesta realizarEncuestaPnl;
    
    public PnlSeguimiento() {
        initComponents();
        agregar();
    }

    private void agregar(){
        resultadoPnl = new PnlEncuestaResultado();
        
        resultadoPnl.setLocation(408,0);
        resultadoPnl.setSize(773,589);
        resultadoPnl.setVisible(false);
        add(resultadoPnl);
        
        realizarEncuestaPnl = new PnlRealizarEncuesta();
        realizarEncuestaPnl.setLocation(408,0);
        realizarEncuestaPnl.setSize(773,589);
        realizarEncuestaPnl.setVisible(true);
        add(realizarEncuestaPnl);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionSeguimiento_Tb = new javax.swing.JTabbedPane();
        realizarEncuesta_Pnl = new javax.swing.JPanel();
        tipo_RE_Lbl = new javax.swing.JLabel();
        seleccion_RE_CBx = new javax.swing.JComboBox();
        resultado_Pnl = new javax.swing.JPanel();
        cursoCapacitacion_R_Lbl = new javax.swing.JLabel();
        cursoCapacitacion_R_CBx = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        opcionSeguimiento_Tb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        realizarEncuesta_Pnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                realizarEncuesta_PnlComponentShown(evt);
            }
        });

        tipo_RE_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo_RE_Lbl.setText("Tipo de Competencia:");

        seleccion_RE_CBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seleccion_RE_CBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tecnología", "Comunicación", "Trabajo en equipo" }));

        javax.swing.GroupLayout realizarEncuesta_PnlLayout = new javax.swing.GroupLayout(realizarEncuesta_Pnl);
        realizarEncuesta_Pnl.setLayout(realizarEncuesta_PnlLayout);
        realizarEncuesta_PnlLayout.setHorizontalGroup(
            realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarEncuesta_PnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tipo_RE_Lbl)
                .addGap(33, 33, 33)
                .addComponent(seleccion_RE_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        realizarEncuesta_PnlLayout.setVerticalGroup(
            realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, realizarEncuesta_PnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(realizarEncuesta_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_RE_Lbl)
                    .addComponent(seleccion_RE_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(486, Short.MAX_VALUE))
        );

        opcionSeguimiento_Tb.addTab("Realizar encuesta", realizarEncuesta_Pnl);

        resultado_Pnl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                resultado_PnlComponentShown(evt);
            }
        });

        cursoCapacitacion_R_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cursoCapacitacion_R_Lbl.setText("Curso de Capacitación:");

        cursoCapacitacion_R_CBx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cursoCapacitacion_R_CBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout resultado_PnlLayout = new javax.swing.GroupLayout(resultado_Pnl);
        resultado_Pnl.setLayout(resultado_PnlLayout);
        resultado_PnlLayout.setHorizontalGroup(
            resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultado_PnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(resultado_PnlLayout.createSequentialGroup()
                        .addComponent(cursoCapacitacion_R_Lbl)
                        .addGap(18, 18, 18)
                        .addComponent(cursoCapacitacion_R_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        resultado_PnlLayout.setVerticalGroup(
            resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultado_PnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(resultado_PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoCapacitacion_R_Lbl)
                    .addComponent(cursoCapacitacion_R_CBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );

        opcionSeguimiento_Tb.addTab("Resultados", resultado_Pnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionSeguimiento_Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 777, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcionSeguimiento_Tb)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void realizarEncuesta_PnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_realizarEncuesta_PnlComponentShown
        resultadoPnl.setVisible(false);
        realizarEncuestaPnl.setVisible(true);
    }//GEN-LAST:event_realizarEncuesta_PnlComponentShown

    private void resultado_PnlComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_resultado_PnlComponentShown
        resultadoPnl.setVisible(true);
        realizarEncuestaPnl.setVisible(false);
    }//GEN-LAST:event_resultado_PnlComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cursoCapacitacion_R_CBx;
    private javax.swing.JLabel cursoCapacitacion_R_Lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane opcionSeguimiento_Tb;
    private javax.swing.JPanel realizarEncuesta_Pnl;
    private javax.swing.JPanel resultado_Pnl;
    private javax.swing.JComboBox seleccion_RE_CBx;
    private javax.swing.JLabel tipo_RE_Lbl;
    // End of variables declaration//GEN-END:variables
}
